### ISSUE TITLE
Image Duplicates in Lightbox when using GatsbyImageSharpFluid_tracedSVG fragments

### ISSUE THREAD

**Issue by LarsBehrenberg** [michelecocuccio/simple-react-lightbox#101]
Hi,

firstly thanks for creating and maintaining this. SRL has really helped me out a lot. 

I have ran into an issue where I am using SRL on a gatsby site with tracedSVG fragments (which currently drastically improves Lighthouse scores) and images show up twice inside the lightbox.

![Screenshot 2020-11-03 at 17 35 23](https://user-images.githubusercontent.com/32539217/97963802-0bfc1a00-1dfb-11eb-81a0-c83150585a2e.jpg)

When using "standard" gatsby image with base64 placeholder images, SRL works just fine. Usually I would just settle with base64 placeholders then, however lighthouse scores drop by 20-30 points compared to using svgs.

Here is a version of the gatsby site using the svg placeholders:
[https://testing-ia-site.netlify.app/impressionism-timeline](https://testing-ia-site.netlify.app/impressionism-timeline)

Here is a version of the gatsby site using base64 placeholders:
[https://impressionistarts.com/impressionism-timeline](https://impressionistarts.com/impressionism-timeline)

I am not quite sure, why this is happening. I would appreciate any advice on how to go about this!

Thanks!

**Comment by michelecocuccio** [comment]
@LarsBehrenberg hello.

I had to add support for the base64 with Gatsby so I guess I will need to add it to the tracedSVG too. There are too many use cases with Gatsby images, and they always produce a different code so it's really difficult to grab the right images every time. 

Could you please show me the code where you are using tracedSVG? Are you using GatsbyImageSharpFluid_tracedSVG? I will try to add a fix on the next release.

Thanks

**Comment by LarsBehrenberg** [comment]
@michelecocuccio thanks for the quick reply!

Just to clarify my use case:
I am using  the [thumbnail custom gallery option](https://github.com/michelecocuccio/simple-react-lightbox#custom-gallery) of SRL wrapping the Gatsby Img in a link with the data-attribute="SRL". As I want the thumbnail (150px wide) to be small and load in with a svg, I query a fixed image using ...GatsbyImageSharpFixed_tracedSVG. The link's href then points to the expanded image source, queried with ...GatsbyImageSharpFluid max 800px wide. I know this is not ideal...

Interestingly enough it still duplicates the image inside the lightbox, although only the fixedImage uses the traced svg fragment. No clue why that is ...

```js
<a  href={image.expandedImage.fluid.src} data-attribute="SRL">
       <Img fixed={image.fixedImage.fixed} alt={image.imageTitle}/>
</a>
```

```graphql
image {
       fixedImage: childImageSharp {
            fixed(width: 150, traceSVG: { color: "#2B2B2F" }) {
                  ...GatsbyImageSharpFixed_tracedSVG
            }
       }
       expandedImage: childImageSharp {
            fluid(srcSetBreakpoints: [800]) {
                  ...GatsbyImageSharpFluid
            }
       }
}
```

Hope this helps!

Thanks lots!

**Comment by michelecocuccio** [comment]
@LarsBehrenberg  thanks. I have released a quick fix in version 3.3.4-2. Can you please let me know if this fixes your issue? Otherwise I will need to spend more time on this.

Thanks

**Comment by LarsBehrenberg** [comment]
@michelecocuccio fixed!

thanks a lot!

**Comment by michelecocuccio** [comment]
Amazing 👍
