### ISSUE TITLE
Lightbox only displays loaded images on mobile (Gatsby)

### ISSUE THREAD

**Issue by ryancybul** [michelecocuccio/simple-react-lightbox#105]
I'm running into an issue where the Lightbox will only display the images that have been lazy loaded on the page even though there are more images in the component.  Once I scroll down the page and new images are lazy loaded they will then display in the Lightbox along with any image that was lazy loaded before it.  If I set the Gatsby Image component to loading="eager" they will all load in the Lightbox, but ideally I'd like to use lazy loading for performance reasons.  It's worth noting I'm only having this issue using Chrome, Firefox, and Safari on iOS and not when using desktop browsers. 

I'm thinking maybe I'm just not using this package with Gatsby correctly.  I saw in the docs there was an example on how to use the package with Gatsby added to the repo, but it looks the example was removed from the repo at some point and it's now in the .gitignore file.  

Any thoughts on how to resolve this issue or does anyone have an example working with lazy loading images working on mobile?

**Comment by michelecocuccio** [comment]
@ryancybul I have tested Gatsby image on mobile with 15 images and I couldn't replicate the issue. There is no difference from mobile / desktop in this instance. The way I use Gatsby Image is the following:

```
            {data.allFile.edges.map((e) => (
              <div key={e.node.id} className="col__lg-4">
                <Img fluid={e.node.childImageSharp.fluid} />
              </div>
            ))}
```

Can you let me know how are you using Gatsby Img component?
Thanks

**Comment by ryancybul** [comment]
@michelecocuccio Thanks for the quick response!  I'm doing something very similar with my image component (see below).  I did some more testing today to see if I could resolve the issue but I didn't have any luck.  Testing on my computer it works 100% but when I publish the site and test it on my iPhone and iPad is when encounter.  It's worth noting that published site will work fine on my laptop as expected.

Originally I thought maybe the issue was because I was using another package for my masonry layout, but I removed that from the equation when testing and still was having the same issue.  

Below is a link to the project I'm working on if you want to take a look at what I'm encountering on your phone or tablet.  The "Commercial" and "Studio" page is using the masonry package and custom options for your package.  The "Blog" page is using the code below, is not using the masonry package, and is using the defaults settings for simple-lightbox-react.  

Let me know if you have any other questions or would like me to do any additional testing.

[https://sharp-williams-1b37f6.netlify.app/](url)

`
const ArtworkCopy = () => {
  const data = studioArtQuery().allWordpressWpMedia.edges;
  const [artwork, setArtwork] = useState([]);

  useEffect(() => {
    setArtwork(
      data.map(function(image) {
        return {
          alt: image.node.alt_text,
          title: image.node.title,
          fluid: image.node.localFile.childImageSharp.fluid,
          id: image.node.id,
          srcSet: image.node.localFile.childImageSharp.fluid.srcSet,
          sizes: image.node.localFile.childImageSharp.fluid.sizes,
          width: image.node.localFile.childImageSharp.original.width,
          height: image.node.localFile.childImageSharp.original.height,
          key: image.node.localFile.childImageSharp.fluid.src,
        };
      })
    );
  }, []);

  return (
    <>
      <SRLWrapper>
          {artwork.map(photo => (
            <div key={photo.id}>
              <Img fluid={photo.fluid} alt={photo.title} />
            </div>
          ))}
      </SRLWrapper>
    </>
  );
};
`

**Comment by michelecocuccio** [comment]
@ryancybul the code is not well formatted and it's a bit difficult to read. Please use triple backticks when embedding code on GitHub. Anyway I tested it on Android using Chrome and it works. I don't have an iPad or an iPhone so I will need to debug them later with some more tools. Is pretty difficult to debug the code on mobile device but I'll let you know once I do some testing.

**Comment by ryancybul** [comment]
@michelecocuccio My apologies on the formatting!  I included triple backticks in my previous comment.  I'm 99% sure this is an iOS issue only as it only.  I reached out to a couple friends of mine who have Android devices and they are saying it works with no problems as well.  I'm still searching for a solution and will let you know what I find out.

**Comment by sathyaram** [comment]
@michelecocuccio - Having this issue too still on iOS. I tried opening the lightbox on a iPhone 10 (Gatsby site, using ImageSharp) and only images that ALREADY lazy loaded actually show up in the lightbox. 
On Android this is fine for some reason.
Test: https://sathyaram.com/portraits

**Comment by LukeHW** [comment]
I had an issue similar to this where I was using both src and srcset to have fallback images. I found out that if I use both src and srcset, lightbox will prefer what is in src. I had a WebP image in srcset and an AVIF image in src. So, my images would display on the page, but not lightbox -- and was messed up only on mobile. Everything worked fine in my browser because it supported both types of images.
