### ISSUE TITLE
Is there a way to filter images?

### ISSUE THREAD

**Issue by kubk** [michelecocuccio/simple-react-lightbox#108]
I'd like to filter the images I want to add to the gallery. It looks like it's not possible now: 
https://github.com/michelecocuccio/simple-react-lightbox/blob/2c63a856efc52cd1b22c564a2bf0d96dfabb92a3/src/SRL/SRLWrapper/index.js#L316

I'd be nice to have an option to override this selector. I'd like to change it to `img[data="gallery"]` and display only those images that contain the `gallery` data attribute. Thoughts? Ready to make a PR.

**Comment by michelecocuccio** [comment]
@kubk hello :) 

This is already implemented and it will be available for the next release. It will be a feature available for the PRO version which I am shipping with the new free version as well. You will have an option to exclude some images by using a `SRLExclude` selector to the images you want to exclude.

Stay tuned for the update coming the next week or so.

Thanks

**Comment by kubk** [comment]
@michelecocuccio Ok, thank you. I'll leave this issue open until the release if you don't mind.

**Comment by michelecocuccio** [comment]
Hello.

this feature has been added to the PRO version of Simple React Lightbox.
You can find out more on the [Simple React Lightbox website](https://simple-react-lightbox.dev).

**Comment by CharlyPoppins** [comment]
Hi, any workaround until the PRO version is back ?
