### ISSUE TITLE
Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by irzhywau** [michelecocuccio/simple-react-lightbox#109]
Hi, 

I got this issue when I try to switch to another page which contains a lightbox. 

I'm pretty sure it's due to react lifecycle that is not well digested by the component which uses `useRef(null)` to reference the SRL container which getting destructed when the component is being to unmount.

https://github.com/michelecocuccio/simple-react-lightbox/blob/e5c821865edcf2ec378f85b238fb3eeed0fadf91/src/SRL/SRLWrapper/index.js#L23

My implementation is quite simple as following 
```javascript
const options = {
  buttons: {
    backgroundColor: 'transparent',
    iconColor: '#555555',
    iconPadding: '7px',
  },
  caption: {
    captionColor: '#555555',
    captionFontSize: '30px',
  },
  settings: {
    overlayColor: 'rgba(243, 246, 251, 0.97)',
  },
  thumbnails: {
    showThumbnails: false,
  },
};

const Compact = ({ children }) => (
  <SimpleReactLightbox>
    <SRLWrapper options={options}>
      { children }
    </SRLWrapper>
  </SimpleReactLightbox>
)
```

I'm wondering what I'm doing wrong here.

**Suggestion**
Would it fix it to add a checking before running the lightbox just to prevent such error to happens

https://github.com/michelecocuccio/simple-react-lightbox/blob/e5c821865edcf2ec378f85b238fb3eeed0fadf91/src/SRL/SRLWrapper/index.js#L314
```javascript
   // array can be null during component lifecycle
   if (!array) {
      return;
   }
   ...
```

**Comment by michelecocuccio** [comment]
@irzhywau thanks.

I never had such issue or anything similar wasn't reported before.
Can you be more specific on what you are exactly doing? You are using a Router to switch on a new page which contains a lightbox? I think the part you referenced about the ref has nothing to do with it. The querySelectorAll seems to be the problem.

I have updated the codebase quite a lot and I am about to release a new version in which that part of the code has been changed so let's check it after I push the update and see if the issue still persist.

Thanks

**Comment by irzhywau** [comment]
yes indeed I use `react-router`. One of the page use `simple-react-lightbox`
I know `querySelectorAll` is the problem, the only place it's being in use in inside `handleDetectTypeOfElements` function.

Unfortunately I don't have any trace of the issue, only the headline.

I tried to set the change and build in my local env and seems working ok. though I created a PR with the few changes if you can review it.

PS. I've been on this issue all the day and was not able to fix it in my project implementation side, these 3 lines in PR just did the trick

**Comment by irzhywau** [comment]
btw, thank you for this amazing work. It really rocks!

**Comment by michelecocuccio** [comment]
Hello.

this has been fixed with the version 3.5.0.
Can you please let me know if you still have this issue?

Thanks

**Comment by irzhywau** [comment]
@michelecocuccio it looks good, no more error with same implementation
thank you
btw, what was the issue that may cause this?

**Comment by michelecocuccio** [comment]
@irzhywau I refactored a lot of code, ad moved the logic inside multiple UseEffect hook (some depends on the data that changes, some don't). In this way during lifecycles methods there shouldn't be any problem as everything is loaded.
