### ISSUE TITLE
<img> not shown if wrapped in a <picture> element

### ISSUE THREAD

**Issue by Papidev** [michelecocuccio/simple-react-lightbox#111]
Hi everyone
I noticed that an `<img> ` is not shown in the lightbox if it's wrapped in a ` <picture> ` element
Only its caption is visualized, both on Firefox and on Chrome.
If I comment the `<picture>` ( and the  `<source>` element), leaving only the bare `<img>` tag,  the lightbox works as usual.

I created this Next.js [Sandbox](https://codesandbox.io/s/amazing-brahmagupta-24n2o) to show the problem 

The code in question is this one
   ```
       <SRLWrapper>
          <figure>
            <a href="/images/brachio-head.jpg" data-attribute="SRL">
              <picture>
                <source
                  srcSet="/images/brachio-head.jpg"
                  media="(max-width: 360px)"
                />

                <img
                  class={style["img"]}
                  src="/images/brachio-panorama.jpg"
                  alt="Brachiosaurus"
                ></img>
              </picture>
            </a>

            <figcaption> A beautiful brachiosaurus</figcaption>
          </figure>
        </SRLWrapper>
```

This is a screenshot
![image](https://user-images.githubusercontent.com/48249114/101670069-05dd0700-3a53-11eb-9c45-f8f3b49606ee.png)

Is there a way to overcome that? 
Or am I doing something wrong?
Thank you

Luca

**Comment by michelecocuccio** [comment]
Hey @Papidev.

I have tested the lightbox with just the picture tag like this
```
<picture>
   <source media="(min-width:650px)" srcset="http://test/image.jpg"} />
   <source media="(min-width:465px)" srcset="http://test/image2.jpg" />
   <img src="http://test/image3.jpg" alt="Flowers" />
</picture>
```
It seems like you are using too many different things (a <figure>, a <a> and the <picture>). Is there a reason for that? Just the <picture> should be fine. Please note that if you resize the browser, the picture will change but you will see a wrong image clicking on the lightbox. This is normal as I can't find a way at the moment to do this. Although if you load the lightbox on each media query breakpoint the correct image is taken so this is working as intended.

**Comment by Papidev** [comment]
Hi Michele
I would like to use `<figure>` to treat the image and its caption as a single entity.
The `<a>` tag , on the other hand , was there because I initially followed your example about the gallery with thumbnails, but I realized that probably I don't need it.
And if I remove the <a> tag , it works.

```
         <figure>
            <picture>
              <source
                srcSet="/images/brachio-head.jpg"
                media="(max-width: 360px)"
              />
              <img
                class={style["img"]}
                src="/images/brachio-panorama.jpg"
                alt="Brachiosaurus"
              />
            </picture>
            <figcaption> A beautiful brachiosaurus</figcaption>
        </figure>
```

About the fact that the clicked image doesn't always match the lightbox image, yes I'm aware of that, in the "real" application I'm trying to solve that thing too.

**Comment by michelecocuccio** [comment]
@Papidev thanks for the clarification.

So does it work with the `<figure>` now? Yes unfortunately is really annoying as JavaScript doesn't change the `src` of the pictures straight away in the DOM, otherwise my lightbox would have pick it up because I am currently targeting the `currentSrc` property. I will have a look in the near future how can this be achieved :) 

Thanks a lot
