### ISSUE TITLE
Opening lightbox causing page content to jump right

### ISSUE THREAD

**Issue by pdugan20** [michelecocuccio/simple-react-lightbox#113]
**Describe the bug**
The entire page jumps to the right when you open the lightbox because the scrollbar width isn't being offset.

**Environment**
Using NextJS (10.0.0) with version 3.5.0.

**To Reproduce**
Please include steps to reproduce the behavior:
1. Open the lightbox on any page that can scroll horizontally.

**Screenshots**
https://user-images.githubusercontent.com/1837100/102582593-c8fabb00-40b7-11eb-9a5c-db20fdfd68c2.mp4

**Comment by pdugan20** [comment]
I'm guessing related to:
https://github.com/michelecocuccio/simple-react-lightbox/commit/bca0e6332aefc5994d2fb9dcfb064e44d084a220

**Comment by michelecocuccio** [comment]
@pdugan20 thanks this has now been fixed in version 3.5.1.
Could you please confirm and close the issue if the issue is fixed? Thanks

**Comment by michelecocuccio** [comment]
@pdugan20 hello.

This is not a bug but is intended. I guess you are using a touchpad? If you plug a mouse you will see that the compensation for the scrollbar is intended. When using a touchpad the behaviour of the scrollbar on a Mac changes.

**Comment by pdugan20** [comment]
Thanks for the quick turnaround! Also did the default transitions between images change? Looks like it's doing an easeIn now?
