### ISSUE TITLE
Can't set images with no extension via props

### ISSUE THREAD

**Issue by wholegroup** [michelecocuccio/simple-react-lightbox#114]
All images on our backend don't have extension. 
We use `simple-react-lightbox` via props `<SRLWrapper elements={elements} />`
It worked before but starting with v3.5 it doesn't because of the new function 
https://github.com/michelecocuccio/simple-react-lightbox/blob/3104a84e722a136c7a0d4104010dfbaf2c670b09/src/SRL/SRLWrapper/detect_types.js#L9
that returns false for urls without image extensions

Looks like a bug

**Comment by michelecocuccio** [comment]
@wholegroup thanks for reporting this. It was working before as I wasn't doing any check using regex.

I am tempted to fix it but I am not sure that this is a bug. What I mean is that I am now checking the type of the file that the user provide to make sure that: 

1. it's a valid image 
2. it's not anything malicious

This is of course is a really basic check, nothing fancy. I don't have a way of detect the type of the image just by the URL without an extension, I will need to do some really annoying stuff just to get the MIME type.
Is there a specific reason why your backend is not passing extensions? I am happy to fix it of course as I want the lightbox to work for anyone but I don't want to remove that check as well.

Happy to listen to your opinion if you have a better idea.

Thanks

**Comment by wholegroup** [comment]
@michelecocuccio,

> Is there a specific reason why your backend is not passing extensions? I am happy to fix it of course as I want the lightbox to work for anyone but I don't want to remove that check as well.

I think it's very common case in non public software (crm/erp/etc) to use urls like:
`https://some/url/file/{id}`
`https://some/url/file?id={id}`
Just because it's easy to implement such api controllers. There is no sense to have beautiful/seo urls. 

> Happy to listen to your opinion if you have a better idea.

Well I see now it is by design. It could be good to see some info about this filter in readme.

Thank you!

**Comment by michelecocuccio** [comment]
@wholegroup ok thanks.
As it doesn't affect the lightbox too much I will release a fix soon by removing the regex check for now. 
Thanks for explaining it to me.

**Comment by lachlansleight** [comment]
Just to chime in here, I have a situation which also is broken by this check - all my images are hosted on Firebase Storage, where the URLs look like this:

`https://firebasestorage.googleapis.com/v0/b/lscom-weeklog.appspot.com/o/2020%2F10%2F13%2FAutoBlinds_Assembly_1.jpeg?alt=media&token=164b863b-e5a3-4cdc-b63d-a95391ae1d7b`

So I'm also unable to use the props option. If you do end up reimplementing a regex check feature, you might want to disregard URL parameters that come after a question-mark character...

**Comment by michelecocuccio** [comment]
@wholegroup @lachlansleight 

Thanks for the feedbacks. This has been fixed in version 3.5.2 which I just released with this hotfix.
