### ISSUE TITLE
PRO Version: clicking video in bottom thumbnails seems to trigger close

### ISSUE THREAD

**Issue by goguda** [michelecocuccio/simple-react-lightbox#115]
Clicking a video in the bottom thumbnails seems to trigger a close event for SRL. Simply clicking you can see the lightbox starts to fade like it's going to close but if released soon enough it will stay open. Holding the click for a bit longer triggers a complete close. This only happens with video thumbnails, image thumbnails are fine.

https://user-images.githubusercontent.com/26887502/103101814-57ef6200-45e7-11eb-8aab-22541d72e53c.mp4

**Comment by michelecocuccio** [comment]
@goguda thank you for reporting this. Well spotted.
I have released a fix for the PRO version on version 1.0.4 which I have just released.

Merry Christmas 🎄

**Comment by goguda** [comment]
> @goguda thank you for reporting this. Well spotted.
> I have released a fix for the PRO version on version 1.0.4 which I have just released.
> 
> Merry Christmas christmas_tree

Real quick fix - thank you!!!! Merry Christmas!!
