### ISSUE TITLE
ESLint error when adding custom properties to img and video tags in TypeScript environment

### ISSUE THREAD

**Issue by lachlansleight** [michelecocuccio/simple-react-lightbox#116]
**Describe the bug**
The following code:

```javascript
<SRLWrapper>
    <video
        width="100%"
        height="100%"
        srl_video_caption="Hello, World!"
    >
        <source src="example.mp4" type="video/mp4" />
    </video>
</SRLWrapper>
```

Produces the following ESLint error:
````
Type '{ children: Element; width: string; height: string; srl_video_caption: string; }' is not assignable to type 'DetailedHTMLProps<VideoHTMLAttributes<HTMLVideoElement>, HTMLVideoElement>'.
  Property 'srl_video_caption' does not exist on type 'DetailedHTMLProps<VideoHTMLAttributes<HTMLVideoElement>, HTMLVideoElement>'
````
Which seems to be the result of using the default video element with custom attributes. I can disable ESLint for these lines, but is there some way around this problem? I'm quite new to Typescript so I might just not be understanding something?

**Environment*
This is in a Next.js app with Typescript and ESLint

**Comment by michelecocuccio** [comment]
@lachlansleight hello.

Simple React Lightbox doesn't use Typescript so the error is related to TypeScript and the fact the I have added custom attributes to a video. React type definition file (by default - index.d.ts when staring with create-react-app) contain list of all the standard HTML elements, as well as known attributes.

In order to allow custom HTML attributes, you need to define it's typing. Do that by expanding HTMLAttributes interface:

```
declare module 'react' {
  interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
    // extends React's HTMLAttributes
    custom?: string;
  }
}
```

In case this doesn't work try to do a google search or to open a question on StackOverflow as this is related to TypeScript and custom attributes. Unfortunately I am not a TypeScript expert but I am planning to convert the entire project to use TypeScript soon probably with the help of someone.

Please let me know if you are successfull.

Thanks

**Comment by lachlansleight** [comment]
Thanks for the fast response!

I'll give that a go, but I think that this error is largely coming from the somewhat dubious practise (IMO) of repurposing normal HTML elements to do extra things. I feel like really these should be custom components, so that my example script would be written something like

```javascript
<SRLWrapper>
    <SRLVideo
        width="100%"
        height="100%"
        videoCaption="Hello, World"
        sources={[
            {
                src: "example.mp4",
                type: "video/mp4"
            }
        ]}
    />
    <SRLImage
        src="example2.jpg",
        alt="An example image",
        caption="This image is just here as an example"
    />
</SRLWrapper>
```

I suppose that's just feedback on the library in-general, but this would also make it very easy to add custom prop type definitions for these custom elements. It also makes it clearer that, for example, the alt text provided for an image is its caption, etc.

For now, I'll try expanding the HTMLProps interface as you suggest and let you know how I go.

**Comment by michelecocuccio** [comment]
@lachlansleight thanks for the Feedback.

I get your point and I really appreciate it in fact I was dubious too!!! I did a little bit of research before implementing the new features and there is nothing wrong adding custom attributes to some HTML tags. In facts HTML5 was an important release as it fully support custom attributes. 

I totally agree with you that using a Component would be more React friendly (and this is what happening behind the scenes anyway). But remember, Simple React Lightbox is born with the idea that you should be able to use the lightbox with  some content that comes from different sources. In this case you are declaring your videos manually so a React component would make totally sense! But what if someone has some videos coming from a WYSIWYG editor? They surely can't put a React component there. 

I totally agree with you anyway, my library is a bit "out of the box" in terms of choices. I look forward to improve it in the future.

**Comment by lachlansleight** [comment]
I ended up fixing my problem according to Yaniv Peretz's answer to [this StackOverflow question](https://stackoverflow.com/questions/54869777/react-typescript-adding-custom-attribute) - by using the spread operator with the SRL props. So the final code looks like this:

```javascript
//somewhere else in the component
const customProps = {
    srl_video_caption: "Hello, World!"
};
<SRLWrapper>
    <video
        width="100%"
        height="100%"
        {...customProps}
    >
        <source src="example.mp4" type="video/mp4" />
    </video>
</SRLWrapper>
```

---

If you are converting supplied HTML elements to custom React components behind the scenes, why not give users the option of using those React components? 

I'm not quite sure what you mean by videos coming from a WYSIWYG editor - surely any video component that could be added would have a source either from an embeddable source like YouTube or Vimeo, or would just be a HTML video directly? Embedded videos and HTML videos could easily be separate components, like `<SRLVideo />` and `<SRLVideoEmbed />`...

I really do feel like providing these basic components would make the whole library make a lot more sense and be more like other react libraries, as well as make it easier to integrate with TypeScript. Just my 2c! :)

**Comment by michelecocuccio** [comment]
@lachlansleight I am glad you have found a solution and thanks for providing the feedbacks.
I will consider maybe using a component approach in the future if it's worth it.

Thanks again :)
