### ISSUE TITLE
Thumbnails + lightbox navigation broken when multiple (wrapped) FSRWrappers in a single page

### ISSUE THREAD

**Issue by lachlansleight** [michelecocuccio/simple-react-lightbox#117]
**Describe the bug**
I have a pretty common situation - multiple posts are displayed on a page, each with an associated image gallery. According to the documentation's recommendation, I wrapped my FSRWrapper component in a Gallery component. However, when I click on any of the images in any of the galleries on the page, the thumbnails displayed are for the last gallery rendered (at the bottom of the page). If I navigate between images, SRL acts as if I was in that final gallery, showing me the next image in the last gallery, rather than the next image in the gallery I should be in.

Perhaps I'm misunderstanding what the documentation recommends when multiple galleries on a single page is desired - the language isn't particularly clear. Here is an example of the code I'm using:

```javascript
import { ImageStub } from "../lib/types"
import Gallery from '../components/Gallery'

const MultiGalleryTest = () => {
    const testImages: string[][] = [
        [
            {
                url: "https://firebasestorage.googleapis.com/v0/b/lscom-weeklog.appspot.com/o/2020%2F12%2F09%2FAudioSwitch_1.jpg?alt=media&token=300a439d-f533-4a39-a218-f382f1521cb4",
            },
            {
                url: "https://firebasestorage.googleapis.com/v0/b/lscom-weeklog.appspot.com/o/2020%2F06%2F02%2FNewDesk_03-1024x759.jpg?alt=media&token=9511237d-b110-40f3-a19a-d4799ab87311",
            }
        ],
        [
            {
                url: "https://firebasestorage.googleapis.com/v0/b/lscom-weeklog.appspot.com/o/2020%2F05%2F27%2FAlarmClockScale_PCB_02-1024x768.jpg?alt=media&token=ae66bf4f-d869-4c6d-8689-26589fa5c40a",
            },
            {
                url: "https://firebasestorage.googleapis.com/v0/b/lscom-weeklog.appspot.com/o/2020%2F05%2F27%2FAlarmClockScale_PCB_01-1024x768.jpg?alt=media&token=4296f774-f638-4c4b-8787-6b12f10a86e7",
            },
        ],
    ];

    return (
        <div>
            {testImages.map((images, index) => {
                return (
                    <div key={index}>
                        <h1>This is an image gallery</h1>
                        <Gallery images={images} />
                    </div>
                )
            })}
        </div>
    )
}

export default MultiGalleryTest;
```

Where my gallery component is basically just a wrapper around `FSRWrapper` that uses a `useEffect` hook to turn the supplied image URLs into elements that FSRWrapper can use.

**Environment*
This is running in next.js 10.0.4 and react 17.0.1, with npm version 6.14.4. My browser is Brave, version 1.18.77.

**Screenshots**
![image](https://user-images.githubusercontent.com/24868085/103434932-2ec07880-4c5c-11eb-8839-cdade0bee77a.png)
Multiple galleries on a single page

![image](https://user-images.githubusercontent.com/24868085/103434937-3d0e9480-4c5c-11eb-9f68-e3146be824a2.png)
Note that despite me having clicked on an image in the first gallery, the thumbnails displayed are those of the final gallery on the page. If I navigate left or right, it is that gallery's images that will be displayed.

**Comment by michelecocuccio** [comment]
@lachlansleight hello.

There is a note in the [documentation](https://simple-react-lightbox.dev/documentation) saying that if you are using multiple Galleries you need to wrap each in it's own **`<SimpleReactLightbox>`** component which holds the context (not the `<SRLWrapper>`.


```
<SimpleReactLightbox>
  <SRLWrapper>
     Gallery 1
  <SRLWrapper/>
<SimpleReactLightbox/>

<SimpleReactLightbox>
  <SRLWrapper>
     Gallery 2
  <SRLWrapper/>
<SimpleReactLightbox/>

```

this should fix your issue. I will also edit the documentation to have a more complete example.

Thanks and happy new year
