### ISSUE TITLE
Zoom with scroll wheel causes image not to be zoomed from mouse position

### ISSUE THREAD

**Issue by JeffMusgrave** [michelecocuccio/simple-react-lightbox#119]
**Describe the bug**
On the demo website, after opening the lightbox and engaging the zoom function, using a scroll wheel to zoom causes the image to move diagonally from top left to bottom right. 

**Environment**
demo site @ https://demo.simple-react-lightbox.dev/

**To Reproduce**
1. click thumbnail.
2. after lightbox opens, click the full size image to engage the zoom functionality
3. use scroll wheel to zoom in and out.

I don't currently have SRL installed on a website, but I was considering it again and noticed this on the demo site and thought I'd chime in!

**Comment by michelecocuccio** [comment]
Hello @JeffMusgrave.

Thank you very much for this. I am aware of this bug which unfortunately comes from an external package that hasn't fixed it yet. I am in the process of making some optimisation in general to the lightbox and it should also either fix this or change the library entirely. 

But in reality is not really a bug as the zoom functionality is working, is just not zooming starting from the mouse position.
I will let you know once I have fixed it.

Thanks
