### ISSUE TITLE
Does not work well on mobile within a gallery

### ISSUE THREAD

**Issue by ajCastiglione** [michelecocuccio/simple-react-lightbox#12]
When using this lightbox with an image gallery, there is no easy way to click out of the image leading to poor UX.

**Comment by michelecocuccio** [comment]
Hey @ajCastiglione. 

Thanks for the feedback. I get your point. I wanted the image on mobile to be as big as they could matching the aspect ratio of the device. I don't want the images to be small on mobile devices. Therefore the outer div is sometimes really big and it prevents closing the light-box on a mobile. I will see how to improve this in the future but you can always use the provided close button. 

Thanks
