### ISSUE TITLE
Provide a className override on images, thumbnails and buttons

### ISSUE THREAD

**Issue by ian** [michelecocuccio/simple-react-lightbox#124]
Directly modifying CSS properties is so old school ;)

Adding the ability to provide a className to each of the elements would make this Tailwind CSS compatible.

**Comment by michelecocuccio** [comment]
@ian hello.

While I appreciate the feedback, please restrain yourself from comment like "is so old school ;)" as they really don't add much to your feedback. I am already working on this and it will be available on the next release.

Thanks

**Comment by ian** [comment]
Just trying to add some humor, apologies if you found it offensive.

Thanks for your work on this project.
