### ISSUE TITLE
Ability to trigger the lightbox WITHOUT SRLWrapper around content, ideally with an onClick

### ISSUE THREAD

**Issue by sbarer** [michelecocuccio/simple-react-lightbox#128]
**Describe the bug**
I'm using a separate library to display my images, egjs/react-infinitegrid, which isn't playing nice with your library.
Unfortunately, wrapping the inifiniteGrid with the SRLWrapper inhibits its ability to load new images/content when the user scrolls down.
I was wondering if theres a way to trigger your lightbox with an onClick-type function, where an SRLWrapper isn't required?

Follow up: I converted my page from using React Component to being a hook, in order to use your openLightbox hook, but it still isn't working. I believe that I have completely followed the demo you kindly provided in codeSandbox, but it still isnt working. 
I have used a button as you have, and was able to get that to work.
However, when I use an image from my other gallery, and its onClick to trigger the lightbox, it still won't work, even though it is providing the exact same parameters as the button.

<img width="828" alt="Screen Shot 2021-02-09 at 2 49 22 PM" src="https://user-images.githubusercontent.com/32526568/107438865-10b12800-6ae6-11eb-831c-014d4e3db0cc.png">
<img width="896" alt="Screen Shot 2021-02-09 at 2 49 01 PM" src="https://user-images.githubusercontent.com/32526568/107438871-127aeb80-6ae6-11eb-93e4-5b22252f4cb0.png">

As you can see in the above screenshots, both the Item/img and the button are calling the same function, shouldOpenLightbox, and I can confirm that the console.log output is exactly the same for both.

Any help would be appreciated, thanks!

**Comment by michelecocuccio** [comment]
@sbarer hello.

The hook I have provided is working as intended, I have tested it with the last release and it works so I am not sure what you are doing wrong in your code. Everything seems fine but if I can't test the code is impossible for me to see what's wrong. 
Also you don't need to convert the number to a string but that shouldn't be the issue. Have you wrapped your entire app with the `<SimpleReactLightbox>` component?

Could you try to reproduce an example on CodeSandbox?

**Comment by sbarer** [comment]
I see. Thank you for your help. After extensive fiddling, I was able to get it to work.
However, In future iterations of this library, I'd love for there to be a way to trigger the lightbox without having to put the content within the SRLWrapper, as that can mess with other components. I feel like there should be a way to just explicitly feed the lightbox a reference to the array of images, and the index of the desired image to display.

Thanks for all your great work, this is by far the best lightbox library ive found!

**Comment by michelecocuccio** [comment]
@sbarer you can pass the `<SRLWrapper>` component is the core logic behind Simple React Lightbox. You don't need to pass image inside it if you don't want to. There is an option to use the Simple React Lightbox with an array of images already, and it's also [documented here](https://simple-react-lightbox.dev/documentation/with-props). There is also a working example in the [demo website.](https://demo.simple-react-lightbox.dev/with-props).

Thanks a lot :)

**Comment by sbarer** [comment]
amazing, thats exactly what I was needing. thank you so much!
