### ISSUE TITLE
Is there anyway to add custom actions/buttons like "Favorite"?

### ISSUE THREAD

**Issue by jonaxd1** [michelecocuccio/simple-react-lightbox#129]
![image](https://user-images.githubusercontent.com/34318586/107864908-e41f4800-6e26-11eb-9405-49f46ac7fae8.png)

**Comment by michelecocuccio** [comment]
Hello @jonaxd1.

You can use React and JavaScript to create a new "like/favourite" functionality. 
At the moment there is no way to add custom buttons as the scope of the lightbox is just to display images. You can use JavaScript to put a new button next to the others and adds any function you like to it.

Thanks
