### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by fearlex** [michelecocuccio/simple-react-lightbox#13]
Great Component, works as expected but I get the following warning within my ap.

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

![Screen Shot 2020-01-28 at 12 52 30 PM](https://user-images.githubusercontent.com/89010/73290839-1551b980-41cd-11ea-85b8-e6f0c5606891.png)

It points to the line where i have the `<SRLWrapper>`

Using npm 6.9.0 and React 16.11.0

Any help is appreciated

**Comment by michelecocuccio** [comment]
Hello. I am not sure this is coming from my light-box to be honest. I don't have any async task. Can you please reproduce an example on a CodeSandbox environment or if you have public repo share it with me so I can have a look? I never got this error with all my testing so it's difficult for me to reproduce it.

**Comment by fearlex** [comment]
Appreciate the help. This is coming from the modal overlay dependency. I'm not doing anything crazy other than calling some data on ComponentDidMount. Either way, I can use this component as all we need is an image to open up, no gallery or anything at all per the clients requirement. I appreciate the help and will use it again in the future. Great Work.
