### ISSUE TITLE
Support for PDF Files

### ISSUE THREAD

**Issue by themudassarhassan** [michelecocuccio/simple-react-lightbox#131]
First of all it is great package. Thanks to all.
What I think is missing is support for PDF files. Like if we have some images and pdfs, images will open but the pdf files do not open at all.

**Comment by michelecocuccio** [comment]
@themudassarhassan thank you for your suggestion.

First of all could I please ask you to label the ticket as a "feature request" as this is not a "bug". Support for PDF and other type of content is being considered, but the lightbox was born to handle images and videos and that's its main purpose for now. I will keep you updated if I will add support for that in the future.

Thanks

**Comment by themudassarhassan** [comment]
Thanks for your response.
