### ISSUE TITLE
Next.js Image component thumbnail

### ISSUE THREAD

**Issue by GP-95** [michelecocuccio/simple-react-lightbox#133]
**Describe the bug**

I'm rendering my thumbnails with the Next.js `<Image />` component and wrapping them in `<a>` tags to link back to the full resolution image for the lightbox. However the lightbox only renders the thumbnail and not the full resolution version which I linked in the `<a>` tag.

**Environment*

- React 17.0.1
- Next.js 10.0.6
- Google Chrome 88.0.4324.190
- Firefox 86.0
- Simple-React-Lightbox 3.6.3

**To Reproduce**

1. Create a Next.js `<Image />` with a "src" that points to a low quality image.
2. Wrap the `<Image />` in a `<a>` tag which points to a high quality version of the image.
3. Click the rendered thumbnail to see the Lightbox contain the low quality image.

**Comment by michelecocuccio** [comment]
@GP-95 Hello, thanks for reporting this.
This will be fixed in the next release :)

**Comment by michelecocuccio** [comment]
@GP-95 hello.
I have added a fix in version 3.6.4. Please check the documentation [here](https://github.com/michelecocuccio/simple-react-lightbox#gallery-with-thumbnails). Adding the data-attribute to the Next image component should fix the issue. 

Many thanks.
