### ISSUE TITLE
Opening lightbox is pushing the page content to the right

### ISSUE THREAD

**Issue by DecadentIpsum** [michelecocuccio/simple-react-lightbox#138]
Describe the bug
The page moves to the right when you open the lightbox.

Environment
NextJS (10.0.6) with version 3.6.4.

To Reproduce
Please include steps to reproduce the behavior:

It happens on any page where I add the package. You can also check on your [codesandBox demo page](https://codesandbox.io/s/simple-react-lightboxss-39wrb?fontsize=10).

**Comment by michelecocuccio** [comment]
@DecadentIpsum hello. This is not a bug, this is intended. As the scroll bar is removed the viewport adapts itself. If you don't like this behaviour you can use the [callback](https://simple-react-lightbox.dev/documentation/callbacks) `onLightboxOpened` and add a margin of `n` px to your html or body. 

Thanks

**Comment by DecadentIpsum** [comment]
Thanks a lot 

> @DecadentIpsum hello. This is not a bug, this is intended. As the scroll bar is removed the viewport adapts itself. If you don't like this behaviour you can use the [callback](https://simple-react-lightbox.dev/documentation/callbacks) `onLightboxOpened` and add a margin of `n` px to your html or body.
> 
> Thanks a lot for the fast response. My bad that i didn't read the docs quite well, thanks again!
