### ISSUE TITLE
CORS blocking videos

### ISSUE THREAD

**Issue by guilhermebellotti** [michelecocuccio/simple-react-lightbox#141]
**Describe the bug**
Hi guys, how are you?
I am trying to add a YouTube video inside the lightbox (I have the PRO version), but the video is not being displayed.
Looking at the browser console, I noticed that a CORS lock is occurring.

**Environment**
I'm use:
- GatsbyJS v2.32.6
- React v17.0.1
- NodeJS v14.16.0
- Google Chrome v89.0.4389.90
- OS Linux Ubuntu 18.04.5

**To Reproduce**
I followed the steps in the documentation, inserting the `<SRLWrapper>` tag and `<a>` tag. I added the `srl_video_thumbnail` and `href` options. Code:

```javascript
<S.ItemsImages
  href="https://www.youtube.com/watch?v=QDYfEBY9NM4"
  srl_video_thumbnail={query.imageSharp.fluid.src}
  srl_video_caption="Caption"
  title="Title"
>
  <Img fluid={query.imageSharp.fluid} />
</S.ItemsImages> 
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7539124/112649835-8e788b00-8e29-11eb-8902-a4a89018e212.png)
![image](https://user-images.githubusercontent.com/7539124/112647586-743dad80-8e27-11eb-8ab3-afa3c45c4127.png)

**Comment by michelecocuccio** [comment]
@guilhermebellotti hello.

Unfortunately there is nothing that I can do about it. This can depend by a number of reasons out of the scope of the package. The video is [working for me in my demo ](https://demo.simple-react-lightbox.dev/video-audio) (if you check the YouTube video it loads fine). The library that I am using for the video is called ["react-player"](https://www.npmjs.com/package/react-player) so if you have issues with the video player please try to check their documentation.

**Comment by guilhermebellotti** [comment]
If change code to Img (Gatsby) to img (HTML), working. But not understend the motive 🤔

```javascript
<S.ItemsImages
  href="https://www.youtube.com/watch?v=QDYfEBY9NM4"
  srl_video_thumbnail={query.imageSharp.fluid.src}
  srl_video_caption="Caption"
  title="Title"
>
  {/* <Img fluid={query.imageSharp.fluid} />  */}
  <img src={query.imageSharp.fluid.src} />
</S.ItemsImages> 
```

I think the problem is something with Img from Gatsby. But I also have no idea what can be
