### ISSUE TITLE
Thumbnail navigation not working correctly!

### ISSUE THREAD

**Issue by NRech** [michelecocuccio/simple-react-lightbox#144]
Hello! First, thank you so much for your great jog with the component!

Second, I'm having a really bad problem, the navigation with "Clicking the thumbs" is not working properly on mobile browsers and MacOS browsers. I click several times and nothing happens, very rarelly it works, and then stops again.

I'm using the basic usage with params, I followed everything the docs says. BTW, the example has the same problem, I can't make it work on mobile Chrome (Android).

Can you please help me?

**Comment by michelecocuccio** [comment]
@NRech hello.

Could you be more specific on the versions that you are using? "mobile browsers" and "MacOS browsers" is a bit generic. I have tested it on Safari both on desktop and mobile on a iPhone and it works perfectly fine. Can you be more specific on the versions you are uising?

**Comment by NRech** [comment]
You are right, I'm sorry, I was in such a hurry.

I tried in other phones (more updated) with Chrome and worked, my iPhone Xr, with Safari, and worked. I'll send the information of the device it didn't worked:

![photo_2021-03-29_18-25-42](https://user-images.githubusercontent.com/6012088/112902616-c64b3100-90bc-11eb-8669-588aaff64269.jpg)

It only happened when the thumb slider was needed, when there was more images than it could fit on screen.

About the other ones, the user never responded back with the information, unfortunately.

Thanks for your answer!

**Comment by michelecocuccio** [comment]
@NRech thanks for this.

I have just tested on an [Nexus 6 device](https://drive.google.com/file/d/1MZIsgKUpbOKqe6woPkKpsgPNv2YAIpS6/view) with the Chrome and it works fine. In general, is really difficult to cover every device, but the library should work on any newish device/browser. If you have a more specific list I will be happy to have a look. Thanks
