### ISSUE TITLE
[HMR] Waiting for update signal from WDS... - Hangup when debugging in vscode

### ISSUE THREAD

**Issue by DylanAlbertazzi** [michelecocuccio/simple-react-lightbox#145]
**Describe the bug**
When I try to launch my chrome debugger in vscode, the debugger gets hung up and stops the debugger from being able to run.
The debug console gives this message:
"[HMR] Waiting for update signal from WDS... "
And the file in simple-react-lightbox-pro where the hangup is.
![Screen Shot 2021-03-30 at 10 49 24 AM](https://user-images.githubusercontent.com/79280505/113033310-bb88ae80-9145-11eb-96d2-3bc78e4567d9.png)

**Environment*
Please state if you are using Create React App, Gatsby or NextJS and their version. Include your version of Node and your version of React. Please also include the browser that you are using and possibly its version.
Create React App
React: "^17.0.1"
Node: v14.15.5

**To Reproduce**
Please include steps to reproduce the behaviour:
1. Run the a vscode debugger with this configuration
 {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome 2",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceFolder}/src"
          },

**Screenshots**

**Additional context**
Thank you for the help!

**Comment by michelecocuccio** [comment]
@DylanAlbertazzi hello.

Sorry but I don't have a clue as I never used Chrome debugger in VS Code. If the lightbox is working correctly in the actual app/website then I am afraid that I can't help with that. 

Thanks
