### ISSUE TITLE
No image in gallery on Firefox

### ISSUE THREAD

**Issue by spaquis** [michelecocuccio/simple-react-lightbox#147]
**Describe the bug**
Hi,
I use your library with nextJS and it's work well on Google Chrome but i have a weird problem with firefox. The image in gallery is replaced by : `data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7`

**Environment*
simple-react-lightbox: 3.6.4
"next": "10.0.4"
Firefox: 86.0.1 

**To Reproduce**

 ```
 <SimpleReactLightbox>
      <SRLWrapper
        options={{
          settings: {
            overlayColor: "rgba(0,0,0,0.43)",
          },
          buttons: {
            showAutoplayButton: false,
            showDownloadButton: false,
            showFullscreenButton: false,
            showThumbnailsButton: false,
            showCloseButton: false,
          },
        }}
      >
      {data.photo.map((photo) => (
        <a href={photo.url}>
              <div style={{ height: "113px", width: "113px" }} className="relative">
                <Image
                  layout="fill"
                  className="rounded cursor-pointer object-cover"
                  src={photo.url}
                />
              </div>
            </a>
        )}
      </SRLWrapper> 
 </SimpleReactLightbox>
```

**Screenshots**
On Firefox : KO
![image](https://user-images.githubusercontent.com/27917715/113444215-bd779980-93f3-11eb-8b79-694ca3a43d06.png)

On Chrome : OK
![image](https://user-images.githubusercontent.com/27917715/113444312-ed26a180-93f3-11eb-8bb6-28b75f56b8ed.png)

Any ideas ? Thanks for your help

**Comment by michelecocuccio** [comment]
@spaquis hello.

First of all you can you please update the lightbox to the latest version? (3.6.5). After you do that you need to make sure that in case like this you add the `srl_gallery_image="true"` to the NextJS image component, or it won't pick up the image correctly.

```
       <a href={photo.url}>
             <div style={{ height: "113px", width: "113px" }} className="relative">
               <Image
                 layout="fill"
                 className="rounded cursor-pointer object-cover"
                 src={photo.url}
                 **srl_gallery_image="true"**
               />
             </div>
        </a>
```

please try it out and let me know.

**Comment by spaquis** [comment]
It's works, thanks for your help
