### ISSUE TITLE
differentiate thumbnail from gallery-image when in lightbox mode.

### ISSUE THREAD

**Issue by arch-stefanozanetti** [michelecocuccio/simple-react-lightbox#15]
Hi, first of all: great plugin!

i just have a question. I'm implementing a lightbox gallery that needs to have a logo as thumbnail and an image as lightbox image.
Imagine that i need to have some thumbnail with logos of mercedes, ferrari, bmw and when I click on a logo I need to see the car image.
This is super simple o achieve using the "GALLERY WITH LINKS" option, But, when I'm in lightbox mode, the thumbnail it's not the car logo, but instead is the car image.

Hoping i make myself clear.
thank you!

**Comment by michelecocuccio** [comment]
Hi @arch-stefanozanetti.

The anchor tag is going to be the image you want to open in the light-box, the img is going to be the thumbnail.

```
<div className="col-md-4 col-6 col-image-with-link">
   <a href="ImageThatYouWantToOpen data-attribute="SRL">
       <img src="YourThumbnail" alt="A small boat" />
   </a>
</div>
````

If you test it in the CodeSandbox example that I have created it works as intended :)

**Comment by arch-stefanozanetti** [comment]
Hi, thank you for the reply!
what i'm trying to say is that, if you look on your codesandblox (in the
imageWithLinks component) and you set the thumbnails to TRUE, you could see
that the thumbnail inside the lightbox is different from the thumbnail used
as img tag.
In  fact, the thumbnail inside the lightbox is the ancor tag image.

thank you.

____________________________________________________
*STEFANO ZANETTI | FRONTEND DEV & ARCHITECT*

Via Antonio Gramsci 56 | 20090 Vimodrone (MI)  |  Tel. 0039.333.4212402

Le informazioni trasmesse attraverso la presente e-mail ed i suoi allegati,
sono diretti esclusivamente al destinatario e devono ritenersi riservati
con divieto di diffusione e di uso nei giudizi, salva espressa
autorizzazione; nel caso di utilizzo senza espressa autorizzazione, verrà
effettuata denuncia al competente Consiglio dell’Ordine Forense per
violazione dell’art. 28 del Codice Deontologico. La diffusione e la
comunicazione da parte di soggetto diverso dal destinatario, è vietata
dall’art. 616 e ss. c.p. e dal d. lgs. n. 196/03.
Se la presente e-mail e i suoi allegati fossero stati ricevuti per errore
da persona diversa dal destinatario, siete pregati di distruggere tutto
quanto ricevuto e di informare il mittente con lo stesso mezzo.

Tutti gli eventuali disegni in allegato sono di mia esclusiva proprietà e
sono sotto la protezione della legge sulla proprietà letteraria. Ne e'
quindi vietata per qualsiasi motivo la riproduzione e la consegna a terzi.





Il giorno ven 7 feb 2020 alle ore 20:13 Michele <notifications@github.com>
ha scritto:

**Comment by michelecocuccio** [comment]
I understand now. 
This is normal behaviour but I will try to implement something soon to change it. 
Thanks

**Comment by michelecocuccio** [comment]
Hello @arch-stefanozanetti.

I implemented your suggestion but I don't think I am going to push it live. From a UI/UX prospective and quoting your example I will say that what you are trying to achieve is not the best solution. Let me explain why:

> Imagine that i need to have some thumbnail with logos of mercedes, ferrari, bmw and when I click on a logo I need to see the car image.

That's all fine. But the moment you open the light-box you are in a separated view (the light-box modal window in this case), where you are viewing a gallery of cars. If I start to showing thumbnails that they are not related to the gallery you will end up with something really weird.

![Screenshot-2020-02-08-at-15 23 16](https://user-images.githubusercontent.com/8071249/74087840-df8fb900-4a87-11ea-9ade-2afcfa390c9c.jpg)

For example in this image the thumbnail is related to the image but is not the image itself. So this behaviour that you want to implement is "Ok" but it doesn't reflect the philosophy of my light-box. 
I can consider it as feature and if it gets upvotes I might implement it! 

Thanks

**Comment by arch-stefanozanetti** [comment]
Thank you for the reply. I understand what you mean and probably it's just
my case and not the common behaviour.

Since you already implemented it, maybe you can suggest me how you adapt it
so I can do the same for my custom project.

Thank you!


Il sab 8 feb 2020, 16:31 Michele <notifications@github.com> ha scritto:

**Comment by michelecocuccio** [comment]
Ok. I have added this in version 2.2.0 because at the end of the day if the user wants to use a thumbnail to be the same of the actual image he will do it himself. So the decision comes from the user and how he uses the light-box. Please update to 2.2.0 to test if it all works as intended.
