### ISSUE TITLE
Two separate lightbox for a single page

### ISSUE THREAD

**Issue by UsamaAshraf82** [michelecocuccio/simple-react-lightbox#150]
I have a unique scenario where i have to use two separate lightbox for a single page

Image of scenario ![Opera Snapshot_2021-05-07_115708_localhost](https://user-images.githubusercontent.com/32302712/117411641-3a36ef80-af2d-11eb-9054-13af1e88772c.png)

when there is one lightbox every thing works fine when there is more than one lightbox thing get messy there 
The Images get interchanging 
The CPU usage got to 70 - 80%

https://user-images.githubusercontent.com/32302712/117412073-c2b59000-af2d-11eb-9a49-4b25a8fa0e3f.mp4

in both component i am using it like this   `<SRLWrapper elements={items} />`

### Environment
 Create React APP
  node version 16.0.0
  npm version 7.10.0
```
   "react": "^17.0.1",
   "react-dom": "^17.0.1",
   "simple-react-lightbox": "^3.6.6",
```

System Configuration
OS : Windows 10 Pro build 19042.928
Processor: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz   2.50 GHz
Ram : 8 GB

**Comment by michelecocuccio** [comment]
@UsamaAshraf82 hello.

Please refer to [the documentation](https://simple-react-lightbox.dev/documentation/#multiple-lightbox-on-the-same-page) on how to implement 2 lightbox on the same page. You need two instances of the `<SimpleReactLightbox>
` component. In regards of the performance, I know at the moment the lightbox is not very optimised to handle multiple lightbox on the same page. This will be fixed when the next major version will be released.

Thanks
