### ISSUE TITLE
Prevent right click in lightbox

### ISSUE THREAD

**Issue by wildpow** [michelecocuccio/simple-react-lightbox#152]
Wondering if there is a way of preventing right click on images. I've done this in my custom gallery component with `          onContextMenu={(e) => e.preventDefault()}` but, it would be nice to have the option in the lightbox.

**Comment by michelecocuccio** [comment]
@wildpow hello, thanks for the feedback.
As you noticed you can achieve this quite easily with JavaScript in generale. I don't think the lightbox should be in charge of something like that but I will consider if it's worth add this feature in the next release. Thanks a lot!

**Comment by JakeAngell** [comment]
It looks like the onContextMenu function is cleared after opening the lightbox. So turning off onContextMenu works for the child img elements in the SRLWrapper but reappears when the full sized image is opened by the ligthbox.
