### ISSUE TITLE
No blocking Error : Cannot read property 'parentElement' of null

### ISSUE THREAD

**Issue by spaquis** [michelecocuccio/simple-react-lightbox#153]
Hi,

**Describe the bug**
I have an error in navigator console when access screen with the gallery :
_offsetParent.parentElement_ => TypeError: Cannot read property 'parentElement' of null

**Environment*
NextJS 

**To Reproduce**
```
<a
    key={photo.uid}
    href={`/_next/image?url=${photo.url}&w=1280&q=75`}
    className="mb-3"
  >
    <Image
      src={photo.url}
      className="rounded cursor-pointer object-cover"
      layout="fixed"
      height="128px"
      width="128px"
      alt={`Photo ...`}
      loading="eager"
      //@ts-ignore
      srl_gallery_image="true"
    />
  </a>
```
It's work well but i have the error on console.

Can you tell me if somethings is wrong ?
Thanks in advance.

**Comment by michelecocuccio** [comment]
@spaquis I just tested with nextjs and I can't see the error. I will try to do some more tests and see what's happening.

**Comment by spaquis** [comment]
Thanks @michelecocuccio for your help.
In addition i'm using this version : 
```
"simple-react-lightbox": "3.6.5",
"next": "10.0.7",
```

**Comment by ma-bourassa** [comment]
Having the same issue with 
```
    "simple-react-lightbox": "3.6.9-0",
    "next": "11.1.2",
```

**Comment by ma-bourassa** [comment]
The error disappear if I remove the prop `srl_gallery_image="true"` but then I get duplicate images.

**Comment by ma-bourassa** [comment]
@michelecocuccio @spaquis 
The problem was the use of `Preact` in my case.
Bye bye Preact
