### ISSUE TITLE
How to create multiple instance with hooks implementation

### ISSUE THREAD

**Issue by nemixe** [michelecocuccio/simple-react-lightbox#155]
i need to put multiple srl wrapper in a single page and one of it can be triggered with a button calling hooks `openLightbox` implementation, is that possible ?

**Comment by michelecocuccio** [comment]
@nemixe hello.
You can't use multiple SRLWrapper in a single page. You need tu use multiple instances of the SimpleReactLightbox as stated in the documentation in order to have multiple galleries. Inside the instance you can have a button that open the images in the correspondent SRLWrapper.

Thanks

**Comment by nemixe** [comment]
@michelecocuccio thanks for answering. okay so i move the simpleReactLightBox inside a component and that component have a button to open srlwrapper, i want to make sure does my approach is correct.

```
import React from 'react';
import PropTypes from 'prop-types';
import SimpleReactLightbox, {
  SRLWrapper,
  useLightbox,
} from 'simple-react-lightbox';

const ModalLightbox = ({ children }) => {
  const { openLightbox } = useLightbox();

  return (
    <SimpleReactLightbox>
      <button type="button" onClick={() => openLightbox()}>
        Open the lightbox
      </button>
      <SRLWrapper>{children}</SRLWrapper>
    </SimpleReactLightbox>
  );
};

ModalLightbox.propTypes = {
  children: PropTypes.node.isRequired,
};

export default ModalLightbox;
```

because it's seems doesnt work for me

**Comment by michelecocuccio** [comment]
Your implementation is wrong unfortunately.

```<SimpleReactLightbox>``` must be higher than the hook, otherwise the hook will never work. You can create an High Order Component if you are familiar with React, or you just simply need to wrap ```<SimpleReactLightbox>``` higher than the ```useLightbox``` hook

**Comment by nemixe** [comment]
thanks!, that works perfectly @michelecocuccio

**Comment by michelecocuccio** [comment]
Glad I could help :)
