### ISSUE TITLE
Next.JS Image tag not parsing

### ISSUE THREAD

**Issue by VsevolodEpinetov** [michelecocuccio/simple-react-lightbox#158]
**Describe the bug**
Next.JS Image tag is not being parsed by the Component if you are using 'Image with overlay' option. Instead of opening lightbox component it opens full image as a file upon clicking.

**Environment*
NextJS 10.1.1

**To Reproduce**
Please include steps to reproduce the behaviour:
1. Create Lightbox gallery using <Image> tag instead of <img> and using overlays
2. Click on any image
3. Full image opens instead of lightbox

**Additional context**
Overlay itself works flawlessly

**Comment by michelecocuccio** [comment]
@VsevolodEpinetov hello

I have released a quick fix in version 1.3.9 (PRO). Can you check if this is fixed now?

**Comment by VsevolodEpinetov** [comment]
Hi, sorry for the delay, it is indeed works as intended now. Thank you for fast response!
