### ISSUE TITLE
How to align the selected thumb to center?

### ISSUE THREAD

**Issue by guilhermefront** [michelecocuccio/simple-react-lightbox#159]
Currently the selected thumb goes to the left edge (see the image), but is possible to put it to the center?
![image](https://user-images.githubusercontent.com/49620737/124320437-4ff21b00-db52-11eb-86e5-40142abb8aa6.png)

**Comment by michelecocuccio** [comment]
@guilhermefront hello, at the moment is not possibile to align thumbnail to the center on mobile. They follow the natural order from left to right. I will add an option in the future to allow alignment on mobile as well. 

Thanks for asking

**Comment by guilhermefront** [comment]
Ok! Thanks for answering :)
