### ISSUE TITLE
'document' build issue with gatsby

### ISSUE THREAD

**Issue by jahlherapath** [michelecocuccio/simple-react-lightbox#16]
Trying to build a site but it keeps failing cause "document" is not available during server side rendering. Am using "gatsby-browser.js" and "gatsby-ssr.js" as per the documentation but it doesn't seem to be working.

**Comment by tsogoo** [comment]
Also in nextjs ssr.

**Comment by michelecocuccio** [comment]
@jahlherapath @tsogoo version 2.6.3 should support NextJS and Gatsby. See the notes on the documentation.
