### ISSUE TITLE
Safari: Fullscreen button doesn't close fullscreen, but opens it.

### ISSUE THREAD

**Issue by juozasm** [michelecocuccio/simple-react-lightbox#160]
**Environment*
Mac os Big Sur Safari.

**To Reproduce**
Please include steps to reproduce the behaviour:
1. Go to safari browser on Mac os
2. Click on fullscreen btn, it will turn on fullscreen
3.  Click on fullscreen btn again, it will NOT turn on fullscreen

**Comment by michelecocuccio** [comment]
@juozasm hello. Thanks for reporting this.

This is currently a limitation of Safari. I am already working on a workaround on this but at the moment if you want to exit fullscreen on Safari you need to press the Escape key
