### ISSUE TITLE
Is it possible to get a clean build without the extra libraries included?, 300kb script is quite expensive for a lightbox

### ISSUE THREAD

**Issue by n-for-all** [michelecocuccio/simple-react-lightbox#164]
**Describe the bug**
Please describe the bug and how/when happens. Try to be concise and describe clearly the action that you have taken prior to encountering the bug.

**Environment*
Please state if you are using Create React App, Gatsby or NextJS and their version. Include your version of Node and your version of React. Please also include the browser that you are using and possibly its version.

**To Reproduce**
Please include steps to reproduce the behaviour:
3. Error

**Screenshots**

**Additional context**

**Comment by michelecocuccio** [comment]
@n-for-all hello, I am in the process of rebuilding the library from scratch. It will be more performant and super small but at the moment I am having some personal issues so I don't know when it will be finished. Also please don't mark an issue as a "bug" if it's just a "question". Thanks
