### ISSUE TITLE
Request: Ability to add attribute/class to areas that should be ignored

### ISSUE THREAD

**Issue by dwise85** [michelecocuccio/simple-react-lightbox#166]
The library has been working great for me thus far, but I've recently brought in a more complex component that is a child of the SRLWrapper, which has many small icons and such that are being loaded into the gallery. This isn't ideal, and I've tried various ways to finagle the Wrapper to smaller areas of the component tree but can't get it quite perfect. Ideally, we'd have some way to label images that should not be loaded into the gallery, which would cleanly solve my problem.

Something like srl_gallery_image="false" would be fine.

**Comment by michelecocuccio** [comment]
@dwise85 Hello. This feature is already available in the PRO version using the `srl_exclude="true"` attribute. You can show an example [here](https://demo.simple-react-lightbox.dev/excluding-elements). Thanks
