### ISSUE TITLE
Could not find declaration file

### ISSUE THREAD

**Issue by jrnesler** [michelecocuccio/simple-react-lightbox#17]
Hello I just updated to your latest version (2.2.0) and Visual Studio Code is giving me the following error:

> Could not find a declaration file for module 'simple-react-lightbox'. '/home/jessica/Development/react-redux-projects/author-portfolio/node_modules/simple-react-lightbox/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/simple-react-lightbox` if it exists or add a new declaration (.d.ts) file containing `declare module 'simple-react-lightbox';`ts(7016)

Any pages that I try to use the lightbox subsequently don't load.

Thank you so much for all you hard work, I truly appreciate it!

**Comment by michelecocuccio** [comment]
Hello @jrnesler.

Version 2.2.0 hasn't added anything related to your error which it seems related to typescript.
Are you using typescript? I haven't created a typescript version of this project yet but it shouldn't matter. By the way there is no "npm install @types/simple-react-lightbox" you should just do "npm i simple-react-lightbox".  Can you let me know if your project is enforcing the use of TypeScript?

Thanks

**Comment by jrnesler** [comment]
Hi @michelecocuccio!
Yes, I am using typescript 3.7.5 in my project.  It didn't seem to have any issues with the previous version of the simple-react-lightbox (i believe i was on version 1.4.3 before I updated.) 

Thanks
