### ISSUE TITLE
Rolling Back to Basic simple-react-lightbox

### ISSUE THREAD

**Issue by sparker888** [michelecocuccio/simple-react-lightbox#176]
I understand that you have had to close simple-react-lightbox-pro due to family circumstances. I wish you and your family the best. 

To weather the storm here, I'm trying to roll back to basic lightbox (without the pro), but npm is telling me that it's Not Found at: https://npm.cloudsmith.io/srl/simple-react-lightbox-pro/simple-react-lightbox

Is this an issue on npm? I have seen no changes on how to install it. To reproduce the steps:

1. npm remove simple-react-lightbox-pro
2. Changed the import name in the component from simple-react-lightbox-pro to simple-react-lightbox
3. npm install simple-react-lightbox

The error should show up at this point. I even tried renaming the url to remove the pro and it requests a login at that point.

I appreciate your situation, but as a paying supporter, I'd simply asking that we be able to npm install simple-react-lightbox until you can return.  This issue is holding up my entire project. Netlify hangs up due to this issue and will not publish updates, so I cannot make any changes to the entire site until this is resolved. I don't have time to completely revamp the galleries as other changes to my site are pressing.

Awaiting your response. 

Thank you!

**Comment by goguda** [comment]
> 2\. Changed the import name in the component from simple-react-lightbox-pro to simple-react-lightbox

I agree with this, was really disappointed to see the pro version pulled from npm, especially as I had paid as well. I understand family issues, but especially after having paid for something, not cool.

**Comment by goguda** [comment]
> > I appreciate your situation, but as a paying supporter, I'd simply asking that we be able to npm install simple-react-lightbox > > > until you can return.
> 
> I agree with this, was really disappointed to see the pro version pulled from npm, especially as I had paid as well. I understand family issues, but especially after having paid for something, not cool.

**Comment by michelecocuccio** [comment]
Hello @goguda . First of all people who asked for a refund have been refunded for the PRO version so no arm was done :) 
@sparker888 if you want to rollback you need to remove the .npmrc file and simply install the package from "npm" not "cloudsmith". The ".npmrc" file points to an external provider. That should be easy enough to solve the issue.

**Comment by goguda** [comment]
> Hello @goguda . First of all people who asked for a refund have been refunded for the PRO version so no arm was done :)

Was not aware of this but does make me feel better looool, thanks for the clarification. Wasn't a huge amount so keep my payment as I still appreciate the OSS work :) It's worked well for our application but will probably end up forking and customizing further in the future. Thank you!

**Comment by michelecocuccio** [comment]
@goguda thanks for understanding and for not wanting a refund. I am in the process of rewriting Simple React Lightbox with a lot of improvements (TS, smaller size, faster performance, better animations etc...). It's halfway done, but between work and personal issues it could take me a little while still. Thanks a lot for understanding.

**Comment by sparker888** [comment]
Thanks for the update. I'm looking forward to the updated lightbox!
