### ISSUE TITLE
Onslide event

### ISSUE THREAD

**Issue by frankyso** [michelecocuccio/simple-react-lightbox#18]
i thanks for this awesome package.
but is there any event trigger in this package?

for example event on sliding start or something like that?

**Comment by michelecocuccio** [comment]
Hello @frankyso.
I haven't added any events to the lightbox as I don't think you really need it but I could think about it.
Why do you need event triggers in your case?

Thanks

**Comment by frankyso** [comment]
I need to integrate this lightbox into react-slick index as a navigator,

thanks you

**Comment by michelecocuccio** [comment]
So you need to open the same image as per the one in the carousel?
I can add the functionality to choose the slide that you want to open. It will be less complicated compared to add event triggers. I am pretty busy with work now but I will see what I can do in the near future.

**Comment by frankyso** [comment]
yeah, i need to integrate at least 3 carousel, as main carousel, nav carousel, and of course your lightbox as zoomed carousel.

sure, good to hear that. 😄 

thanks

**Comment by michelecocuccio** [comment]
@frankyso for your information I have added callbacks and showed an example with the slick carousel. Please upgrade to version 2.5 :)
