### ISSUE TITLE
Zooming on image results in the image moving to the right on larger viewports.

### ISSUE THREAD

**Issue by JeffMusgrave** [michelecocuccio/simple-react-lightbox#22]
![image](https://user-images.githubusercontent.com/1578618/78272906-1d371e00-74dc-11ea-9692-53708f14435a.png)

After clicking an image to view as a lightbox, when clicking again to zoom, the image moves to the right.  it is impossible to move left beyond that point. It seems to happen when the browser's viewport is large (or possibly just wider). I'm on a 2560x1440 display, and even around 1600px width this issue starts to occur. It might have to do with the relative width of the image itself though.

Here's a video of it in action: https://i.imgur.com/L5P7Sdb.mp4

**Comment by michelecocuccio** [comment]
@JeffMusgrave Thanks I have noticed this bug yesterday as well. To be honest I am not a big fan of the module that I am using to pinch to zoom as it has many issues. I will see if I can fix it otherwise I will consider moving to another library or drop the functionality for now. Thanks

**Comment by michelecocuccio** [comment]
@JeffMusgrave that should work better now. I am still having some issues with this library when implementing it with React but the image should zoom better now.

**Comment by JeffMusgrave** [comment]
Thanks for getting to it so quickly. It does seem to function better though it does a bit of a weird animation to get there. when clicking zoom the image seems to slide in from the top left. Also if you double click outside of the image once or twice it'll actually animate right off the viewport. Tricky stuff!

**Comment by michelecocuccio** [comment]
@JeffMusgrave I appreciate the thought and the reporting you are giving me :) Yeah this library is good but it doesn't work well with React probably because the component mounting and un-mounting. That's why I marked it as "experimental" and I am trying to write my own "panzoom" functionality! I will get there at some point 👍 For now is just an "optional" that I am offering that can be easily disabled if it's causing issues.

Thanks a lot for your feedbacks :)

**Comment by JeffMusgrave** [comment]
Hey, I know the pan and zoom functionality is experimental, but I was thinking you might take a look at [Framer Motion](https://www.framer.com/motion/). It's similar to something like React Spring, but a lot easier to use and actively maintained. Plus, being spring based, it handles interactions really well. So all those swipe, pan, and zoom animations/interactions should be a lot easier to deal with.

**Comment by michelecocuccio** [comment]
@JeffMusgrave thanks for the suggestion. I am already using Framer Motion the animations of the slides. I am already thinking about adding pan-zoom with it but I will experiment with it and see what I can do for the next release :) Also pan-zoom works a little bit better now compared than before. Thanks for the suggestion anyway.

**Comment by JeffMusgrave** [comment]
Oh, well now I feel stupid hah. I also just noticed you added some spring animations as well! Thanks for the good work!

**Comment by michelecocuccio** [comment]
@JeffMusgrave don't feel stupid! 

Yep, version 3.0 added a lot of cool new things. The library I am using now takes care of pan-zoom including wheel, drag, boundaries etc. If I have to translate this logic using framer motion I will have to do everything by myself but it seems like a nice thing to do and I am already working on it :)
