### ISSUE TITLE
Broken demo

### ISSUE THREAD

**Issue by konstantin24121** [michelecocuccio/simple-react-lightbox#23]
App crushed after "Open Lightbox" button was clicked

**Comment by michelecocuccio** [comment]
Hi @konstantin24121. Which demo? The one CodeSandbox? Can you be more specific please?

**Comment by konstantin24121** [comment]
Hm, strange. All is fine now. I dunno what happened two days ago, but I had a crash here https://simple-react-lightbox.dev/ after click to "Open Lightbox". I think you can close iss, sorry to disturbing
