### ISSUE TITLE
No need to compensate the scrollbar width on Mac OS

### ISSUE THREAD

**Issue by ElForastero** [michelecocuccio/simple-react-lightbox#24]
Nice library. 👋

Mac OS scrollbars behave diffenently.
There's no need to shift the content. Otherwise it causes a content jump to the left and an empty space.

https://github.com/michelecocuccio/simple-react-lightbox/blob/f62770b6e2aad19d1f40400617d5e9913454a0ac/src/SRL/SRLLightbox/SRLLightboxGallery/index.js#L375

![image](https://user-images.githubusercontent.com/5102818/78472134-98503c80-7747-11ea-8364-4f150497cc7c.png)

**Comment by michelecocuccio** [comment]
@ElForastero thanks. I removed it for now.
