### ISSUE TITLE
Issue after recent changes

### ISSUE THREAD

**Issue by mkhoussid** [michelecocuccio/simple-react-lightbox#25]
Just and FYI, I ran into an issue, [Stackoverflow](https://stackoverflow.com/questions/61085975/unable-to-deploy-to-heroku-no-changes-were-made) post. I ended up commenting out all instances of `simple-react-lightbox` for now, because I was not able to deploy my app to Heroku otherwise.

Not sure where the issue arose from, but I'll come back to this project closer to going live, because there are other things to develop for now.

Cheers.

**Comment by michelecocuccio** [comment]
@mkhoussid are you using 2.6.4? I had the same issue just after I published it. It wasn't happening when working locally. I removed the node_modules and yarn.lock and the dist folder and built everything again. I am not using fast-deep-equal/react so it must be a dependency that was causing that issue. Can you try again and let me know?

**Comment by michelecocuccio** [comment]
By the way I tried on a fresh installation using create-react-app and it worked fine.

**Comment by michelecocuccio** [comment]
I have also tried on a fresh installation using nextJS and Gatsby and it worked fine.

**Comment by mkhoussid** [comment]
Thank you for your swift reply! I will try this out after work and get right back to you.

**Comment by sadrzadehsina** [comment]
I have also the same issue. cleaning up the `node_modules` and rebuild the entire project does not help.

**Comment by michelecocuccio** [comment]
@sadrzadehsina Thanks. I am unable to replicate the issue. I had it once and now it's not happening again to me.
Could you please provide more information? Are you using Gatsby, NextJS or CRA? Have you tried to also remove your "yarn.lock" and "dist" folder apart from removing the ```node_modules``` folder? Are you on version 2.6.4? You can always rollback to version 2.5.5 which is stable before all the changes.

**Comment by sadrzadehsina** [comment]
@michelecocuccio Thanks for your quick reply. v2.6.5 is the same, I have the same issue with that version. However I changed to the v2.5.5 and now it works fine.

**Comment by michelecocuccio** [comment]
@sadrzadehsina thanks. It will be helpful if you could tell me what are you using so I can try to replicate the issue and fix it for everyone. Gatsby? CRA? NextJS. Also which version of React are you using. That will be much appreciated.

**Comment by sadrzadehsina** [comment]
Sure, I am building my app using docker with the following versions. I am not using Gatsby, Create-React-App, or NextJS at all.

- React v16.12.0
- Webpack v4.41.2
- Node v10.15.0
