### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by hayhaydz** [michelecocuccio/simple-react-lightbox#26]
Hey,

I love the lightbox so great work! I just thought a suggestion would be a download button, I understand that I can just right-click and select "Open image in new tab" however I don't think that all of my users would find that entirely intuitive to them. Regardless of whether this seems like a useless suggestion, you've done a great job with the lightbox so far so well done and Thank you!

**Comment by michelecocuccio** [comment]
@hayhaydz thanks! :) 
This is definitely a very good idea! I appreciate it a lot 👍 I will add this on the next release for sure.
