### ISSUE TITLE
Lightbox change image when previews scrolled

### ISSUE THREAD

**Issue by konstantin24121** [michelecocuccio/simple-react-lightbox#32]
When I try scroll previews lightbox change main image. I guess it is wrong behaviour for users, what do you think? 
Also would be nice if preview box have autoscroll to current position. If you open on mobile one of last images current preview image will be hidden
![image](https://user-images.githubusercontent.com/9361325/79691630-77b8d400-8269-11ea-8f21-92d6d1643463.png)

**Comment by michelecocuccio** [comment]
@konstantin24121. Sorry I don't understand fully what you mean. I am aware that the thumbnails are not ideal at the moment on mobile. Like going to the image when swiping etc. I will try to improve them in the near future.

**Comment by pateljoel** [comment]
Just tested this, this issue keeps happening for me but using this on the web.
