### ISSUE TITLE
Is there a way to set autoplay to true?

### ISSUE THREAD

**Issue by dmitriyaa** [michelecocuccio/simple-react-lightbox#33]
Hi, thanks for the lib, it's really cool.
I browsed documentation, and I think `autoplay: true` is not an option.
Also was not able to do it with callbacks, since we don't have much access in the callbacks.
Could you please add this feature?

p.s. it's not a bug, I clicked on it by mistake xD

**Comment by michelecocuccio** [comment]
Thanks @dmitriyaa.
I might consider adding this on the next release :)

**Comment by dmitriyaa** [comment]
@michelecocuccio when is the next release? :D Meanwhile is there a way for me to add this to my project?

**Comment by michelecocuccio** [comment]
@dmitriyaa sorry I don't really now :) Maybe I can add it during the weekend as I am really busy with work right now!

For now you could simulate a click on the Play button like this
```document.querySelector('.SRLAutoplayButton').click()```
This will trigger the autoplay.

**Comment by dmitriyaa** [comment]
@michelecocuccio yeah, I thought about it, but `onLightboxOpened` callback is not very reliable to trigger click. I've tested it and sometimes it's called 2 times on open, and if you try to scroll while lightbox is open, it is triggered 100 times.

**Comment by michelecocuccio** [comment]
@dmitriyaa I will have a look, I haven't tested the callback fully since the last release. I will definitely have a look.
You can use that snippet without using it in the callback to be honest. But for now that's the only solution I can give you I am afraid.

Thanks for pointing out the issue with the callback!

**Comment by dmitriyaa** [comment]
@michelecocuccio sure, no problems. What would be another way to use that snippet? The button should be triggered only once the modal window is opened right?

**Comment by dmitriyaa** [comment]
@michelecocuccio, figured it out, set your snippet on click on image container, thanks!
