### ISSUE TITLE
Overlay effect on thumbnails

### ISSUE THREAD

**Issue by fredleput** [michelecocuccio/simple-react-lightbox#36]
**Describe the bug**
if i use this "markup" lightbox works

```
{post.diaporama.map(image => (
  <div key={image.id}>
    <a href={image.srcLarge} data-attribute="SRL">
      <img source={image.srcMin} className="img-fluid" alt={post.titre} />
  </a>
</div>				
))}
```
but if i use this one lightbox effect is broken,

```
{post.diaporama.map(image => (
  <div key={image.id}>
  <a href={image.srcLarge} data-attribute="SRL">
    <img source={image.srcMin} className="img-fluid" alt={post.titre} />
      <div className="post-icon">
        <FontAwesomeIcon icon={faExpand} size="3x" />
      </div>
    </a>
  </div>				
))}
```

when a is hovered, my css make div.post-icon overlay it completly, i think issue is there, click handler should receive the wrong target : my div.post-icon intead of a with data-attribute.
I also tried to put data-attribute on my div.post-icon but it didn't solved the problem.
Any clue about that ?

i took 4 screenshots :

- lightbox works (first markup)
![gallery-works](https://user-images.githubusercontent.com/3998154/80156554-820a0380-85c4-11ea-9da4-1934f0c2022a.png)
![lightbox_works](https://user-images.githubusercontent.com/3998154/80156570-8a623e80-85c4-11ea-80a9-eaa6000265dd.png)
- lightbox is broken (second markup)
![gallery-broken](https://user-images.githubusercontent.com/3998154/80156590-9948f100-85c4-11ea-9489-84251e5990a8.png)
![lightbox-broken](https://user-images.githubusercontent.com/3998154/80156596-9ea63b80-85c4-11ea-9d56-16f544984112.png)

i use Create React App. react version is 6.13.4. tested under debian 10, chrome 81.0.4044.122

Thx,
Fred
Brittany - France

**Comment by michelecocuccio** [comment]
@fredleput sorry is a bit difficult to understand from the screenshot. I think the problem is that you have a <FontAwesome> component that I suppose it gives you back another image. To use the light-box you can only have 1 nested image after the `data-attribute="SRL"`. I will look in to this on the next release but I doubt there is something I can do about it. For now what I could suggest you is that you display the icon on hover in a different way.

**Comment by fredleput** [comment]
there's only 1 nested image : icon is not a img tag but a svg...

**Comment by michelecocuccio** [comment]
@fredleput I understand. But the fact that you said the the normal markup is working right?

> if i use this "markup" lightbox works
> 
> ```
> {post.diaporama.map(image => (
>   <div key={image.id}>
>     <a href={image.srcLarge} data-attribute="SRL">
>       <img source={image.srcMin} className="img-fluid" alt={post.titre} />
>   </a>
> </div>				
> ))}
> 

```

If that's the case it means the something is conflicting and it's likely being the other `<div>` or the `<FontAwesome>` component. As I mentioned, I never tested my light-box to include multiple "things" inside. I will do some testing when I can but for now I can't consider this a bug but more a wrong implementation of the light-box. I understand you might need an icon inside so on my next release I will see what happens with Svgs or other "elements" inside.

Thanks
