### ISSUE TITLE
Feature request: options | disable keyboard-controls

### ISSUE THREAD

**Issue by cqx931** [michelecocuccio/simple-react-lightbox#37]
Thank you for making simple-react-lightbox, I really like it!
It would be nice if there is an option for disabling keyboard-controls for SRL.

In my project, I have another component in my app that uses keyboard-controls. So I don't want it and SRL to be triggered at the same time.

**Comment by michelecocuccio** [comment]
@cqx931 Thanks, that's a really good idea that I already had in mind. I will make sure I will put it on the next release. I am working a lot at the moment but I should have to release a new version very soon. Thanks a lot :)

**Comment by cqx931** [comment]
Thank you and look forward to the new release!

**Comment by michelecocuccio** [comment]
@cqx931 hello! This has ben now added in version 2.8. Please, read the documentation carefully because the options are now passed a little bit differently. Thanks :)
