### ISSUE TITLE
Access `object` from `onLightboxOpened`? 

### ISSUE THREAD

**Issue by iammatthias** [michelecocuccio/simple-react-lightbox#38]
Is there a way to access the `object` that from `onLightboxOpened` or `onLightboxClosed`? I would like to log the image that is displayed when user opens or closes the gallery. 

Ex. 

```
 const callbacks = {
    onSlideChange: object => handleSlideChange(object),
    onLightboxOpened: object => handleLightboxOpen(object),
    onLightboxClosed: object => handleLightboxClose(object),
  }

  function handleSlideChange(object) {
    console.log(object)
    return object
  }

  function handleLightboxOpen(object) {
    console.log(object)
    return object
  }

  function handleLightboxClose(object) {
    console.log(object)
    return object
  }
```

**Comment by michelecocuccio** [comment]
@iammatthias thanks, I will make it available with the next release :)

**Comment by iammatthias** [comment]
Thank you!

**Comment by michelecocuccio** [comment]
@iammatthias hello! This has ben now added in version 2.8. Please, read the documentation carefully because the options are now passed a little bit differently. Thanks :)

**Comment by iammatthias** [comment]
I'll take a look! Thank you so much!

**Comment by iammatthias** [comment]
Really love the new syntax for the options. It's a lot more readable now.
