### ISSUE TITLE
Blocked by CORS policy: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by hayhaydz** [michelecocuccio/simple-react-lightbox#39]
Hi again,

Great work on adding the download button, my issue is that I am using an AWS S3 bucket for my photography gallery of images. 

Now AWS doesn't seem to like that the fetch is being made I believe without an origin header but I'm not entirely sure what the exact solution is.

You can see your amazing lightbox [here](https://hayhaydz.tk/photography) along with the subsequent error when clicking the download button in the console log.

Thank you so much again!

**Comment by michelecocuccio** [comment]
@hayhaydz sorry to hear that.

This has nothing to do with the light-box. Unfortunately Chrome 65 removed support for the download attribute on anchor elements with cross-origin hrefs. I could use a really messy workaround. I will see if I can change that with the next release by using "fetch" or something else.
