### ISSUE TITLE
Media Query

### ISSUE THREAD

**Issue by Mellas84** [michelecocuccio/simple-react-lightbox#4]
Everythig worked brilliant, until it didnt. I can style everything through a css file but cant modify any component inside the lightbox with media queries. Any other component i can style just fine.

**Comment by michelecocuccio** [comment]
Hello @Mellas84. 

Can you tell me exactly what are you trying to modify? When you say "components inside the lightbox" you mean like the buttons and the image? if you can describe what you are trying to do and maybe put the code on a code-sandbox it will be great. 

Thanks

**Comment by Mellas84** [comment]
im trying to change the width and height of the images, i just tried with display:none and it worked like it should

**Comment by Mellas84** [comment]
oh well, i cant seem to edit any position attribute, width or height from @media, but transform seems to work brilliantly so ill just use that for the time being i guess.

**Comment by michelecocuccio** [comment]
Ok @Mellas84. I am glad you found this solution.

I will probably add an option to resize the images if this becomes a requested feature. I strongly suggest to not change the size of the images as this might have unexpected consequences.

Many thanks :)
