### ISSUE TITLE
"closeLightbox" equivalent of "openLightbox"

### ISSUE THREAD

**Issue by hectormerla** [michelecocuccio/simple-react-lightbox#41]
Hi! I am using this lightbox and it's great! I notice there's no "close" equivalent of "openLightbox" in the useLightbox() hook.

Is there a way I can close programmatically the lightbox? I notice I can't close with scape key, I wanted to create a custom handler for that but couldn't find an `closeLightbox` method.

Maybe the useLightbox hook could return an object with different methods like an  `openLightbox` and `closeLightbox`. Or maybe there's another way?

**Comment by michelecocuccio** [comment]
@hectormerla this was requested before.
I will add an hook to close the light-box on the next release. The ESC key is a bug, as it was implemented and it's not working now. I will have a look soon and implement a fix as fast as I can.

Thanks

**Comment by michelecocuccio** [comment]
@hectormerla hello! This has ben now added in version 2.8. Please, read the documentation carefully because the options are now passed a little bit differently. Thanks :)

**Comment by hectormerla** [comment]
@michelecocuccio Wow, your response was fast, I updated the package and everything works like a charm! Thank you!
