### ISSUE TITLE
Using an onClick event to display lightbox in the same component

### ISSUE THREAD

**Issue by dmorda** [michelecocuccio/simple-react-lightbox#44]
I have a page where I want to display three photo galleries. Each gallery will have an image on the page and when you click it, i want it to display the photos for that gallery. So in theory, this sounds like I'd need to use the onClick event to display the lightbox for a specific gallery.

Is this possible?

While working on it, I couldn't get the onClick event to work even with the simplest of examples so I'm guessing I'm doing something wrong. Here's the code that doesn't work.

```
import React from "react"
import { SRLWrapper, useLightbox } from "simple-react-lightbox"

const PhotoGallery = () => {

  const { openLightbox } = useLightbox()

  return (
    <div>

        <button onClick={() => openLightbox()}>
            Open the lightbox
        </button>

        <SRLWrapper>
          <img src="https://fakeimg.pl/250x100/" alt="Some stuff" data-attribute="SRL" />
        </SRLWrapper>

    </div>
  )
}

export default PhotoGallery
```

The error I get is this...

```
Uncaught TypeError: h.dispatch is not a function
    at index.es.js:7
    at t (index.es.js:7)
    at index.es.js:7
    at a.<anonymous> (index.es.js:7)
    at a../node_modules/simple-react-lightbox/dist/index.es.js.t.emitEvent (index.es.js:1)
    at a../node_modules/simple-react-lightbox/dist/index.es.js.a.complete (index.es.js:7)
    at a../node_modules/simple-react-lightbox/dist/index.es.js.a.progress (index.es.js:7)
    at index.es.js:7
```

Before I pull my hair out, what might I be doing wrong?

**Comment by michelecocuccio** [comment]
@dmorda hi,
As per the documentation:
_Note: if you need multiple instance of the light-box in one page you should wrap each one in it's own <SimpleReactLightbox> component._

So if you have 3 galleries on the same component, you need to wrap each and every one in their own <SimpleReactLightbox> component so for example

```
<SimpleReactLightbox>
   <ButtonWithHook />
   <SRLWrapper>
    GALLERY 1
  <SRLWrapper/>
<SimpleReactLightbox />

<SimpleReactLightbox>
   <ButtonWithHook />
   <SRLWrapper>
    GALLERY 2
  <SRLWrapper/>
<SimpleReactLightbox />

<SimpleReactLightbox>
   <ButtonWithHook />
   <SRLWrapper>
    GALLERY 3
  <SRLWrapper/>
<SimpleReactLightbox />
```
the logic of your hook should be inside the <SimpleReactLightbox> instance, maybe in a separated component (in the example above the hook will be in a <Button /> component)

**Comment by dmorda** [comment]
That worked like a charm, thank you!

Only one thing left I haven’t figured out. Is there a way to hide the images on the screen and display a button like “Launch gallery” that then displays the lightbox for the images?

**Comment by michelecocuccio** [comment]
@dmorda you don't need to pass images in the ```<SRLWrapper />```. Please refer to the documentation "[passing images in an array](https://github.com/michelecocuccio/simple-react-lightbox#declaring-images-in-an-array)".

**Comment by dmorda** [comment]
That worked like a charm, thanks so much!
