### ISSUE TITLE
Uncaught TypeError: p.dispatch is not a function

### ISSUE THREAD

**Issue by nadernt** [michelecocuccio/simple-react-lightbox#45]
**Describe the bug**
I tried all the examples. It gives below error. I think it is a bug. I tried older versions of library same result. Any help will be appreciated. 

index.es.js:7 Uncaught TypeError: p.dispatch is not a function
    at index.es.js:7
    at t (index.es.js:7)
    at index.es.js:7
    at a.<anonymous> (index.es.js:7)
    at a.t.emitEvent (index.es.js:1)
    at a.complete (index.es.js:7)
    at a.progress (index.es.js:7)
    at index.es.js:7
(anonymous) @ index.es.js:7
t @ index.es.js:7
(anonymous) @ index.es.js:7
(anonymous) @ index.es.js:7
t.emitEvent @ index.es.js:1
a.complete @ index.es.js:7
a.progress @ index.es.js:7
(anonymous) @ index.es.js:7
setTimeout (async)
t @ index.es.js:7
t.emitEvent @ index.es.js:1
c.confirm @ index.es.js:7
c.onload @ index.es.js:7
c.handleEvent @ index.es.js:7
load (async)
c.check @ index.es.js:7
(anonymous) @ index.es.js:7
a.check @ index.es.js:7
setTimeout (async)
a @ index.es.js:7
a @ index.es.js:7
r @ index.es.js:7
o @ index.es.js:7
(anonymous) @ index.es.js:7
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164

**Comment by michelecocuccio** [comment]
@nadernt have you wrapped your App with the ```<SimpleReactLightbox />``` component?

**Comment by nadernt** [comment]
> @nadernt have you wrapped your App with the `<SimpleReactLightbox />` component?

Thanks, that was the issue. Now everything is fine. Is there any option to show thumbnails horizontally and scrollable? This is a good feature because it saves screens area for the main slide.

**Comment by michelecocuccio** [comment]
@nadernt please read the docs carefully as it wasn't an issue 👍 but I am glade you solved it.
Expect great improvements for the thumbnails in the next release 😀. I will launch it either today or tomorrow.
