### ISSUE TITLE
Is it possible to have both images declared in array and explicitly rendered wrapped in the same SRLWrapper?

### ISSUE THREAD

**Issue by knkevinlai** [michelecocuccio/simple-react-lightbox#46]
This is the best react lightbox gallery library I have found. Thanks!

As the question in the title, let's say I have 8 images rendered inside a <SRLWrapper/>, but I would like to have 3 extra hidden images in the same <SRLWrapper images={[ ...extraImages ]}/> that will only be shown on the popup lightbox together with other 8 images. Is there any way to implement this by using the latest version?

P.S. other idea: is it possible to have multiple <SRLWrapper/> inside one <SimpleReactLightbox/> to achieve the same objective above?

Thank you!

**Comment by michelecocuccio** [comment]
@knkevinlai hi. Thanks :) 

This is not possibile for now and I don't plan to add this as it's against some patterns that I use when programming. Surely if you want to this you could do it the other way around and without wrapping the images in the ```<SRLWrapper>``` component and just using the hook. Like this:

```
// Import the Simple React Lightbox hook
const { openLightbox } = useLightbox()

// This contains all your images (each image is an object with source, caption etc... as shown in the documentation)
const allMyImages = [{img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11}]

// Don't pass any image inside the component, just the prop with the images
<SRLWrapper images={allMyImages} /> 

// Your gallery, however you do it, only display 8 images and you use the hook to open the image that you wan (remember that is 0 index based)
<img src="../src/img1.jpg onClick={() => openLightbox(0)} />
<img src="../src/img2.jpg onClick={() => openLightbox(1)} />
<img src="../src/img3.jpg onClick={() => openLightbox(2)} />
<img src="../src/img5.jpg onClick={() => openLightbox(3)} />
... 
```

I think this fully accomplished what you want to do. Using the hook gives you flexibility

**Comment by knkevinlai** [comment]
@michelecocuccio Thank you for this clean code example.

I have tried this work around and it works like a charm. And I am fine with this pattern. 😊

(sorry this issue is not a bug but should be a question instead)
