### ISSUE TITLE
Overflow hidden style not removed in IE11 when lightbox is closed

### ISSUE THREAD

**Issue by dmorda** [michelecocuccio/simple-react-lightbox#47]
**Describe the bug**
When the lightbox is opened on IE 11 the body tag is modified to become the following:

```<body class="SRLOpened" style="overflow:hidden">```

When the close button is pressed in the lightbox, it removes the "SRLOpened" class, but not the style attribute making it no longer possible to scroll on the page.

```<body style="overflow:hidden">```

**Environment*
"gatsby": "^2.21.24",
"gatsby-image": "^2.4.3",
"simple-react-lightbox": "^2.8.0-5",

**To Reproduce**
Please include steps to reproduce the behaviour:
1. Go to [this website](https://simple-react-lightbox.dev/) in IE11
2. Open the lightbox
3. Close the lightbox
4. Try to scoll on the page

**Screenshots**
<img width="1439" alt="Screen Shot 2020-05-17 at 4 18 09 PM" src="https://user-images.githubusercontent.com/614613/82159121-0c5b2580-985a-11ea-9e99-0f599476003d.png">
<img width="1440" alt="Screen Shot 2020-05-17 at 4 18 17 PM" src="https://user-images.githubusercontent.com/614613/82159123-0cf3bc00-985a-11ea-9975-4535a3b18901.png">

**Comment by michelecocuccio** [comment]
@dmorda thanks, good catch! 

Apparently setting the value to `null` is not working on IE11. I have fixed it already and it will be ready for the next release. I have changed flex-box for CSS grid in some part for the next release and I am making sure that it works on IE11. Unfortunately I am having a lot of issues right now which are delaying the next release but stay tuned as there are tons of improvement coming.

**Comment by dmorda** [comment]
Sounds good.

For anyone else experiencing the issue, here's the workaround I put in place to address it.

```
const removeOverflow = (args) => {
  if (typeof document !== 'undefined' && typeof window !== 'undefined') {
    const el = document.querySelector('body')
    el.style.overflow = ''
    console.log('removed overflow')
   }
 }

const callbacks = {
  onLightboxClosed: args => removeOverflow(args)
}
```

And then in the SRLWrapper...
```
<SRLWrapper options={options} callbacks={callbacks}>
[...]
</SRLWrapper>
```

**Comment by michelecocuccio** [comment]
@dmorda fixed in version 3.0.0

**Comment by dmorda** [comment]
Works like a charm, great work on the new release. Really like the changes to the thumbnails and how they stay in sync while you navigate them. Only thing I found is that you can't seem to swipe the thumbnails on mobile any longer. Is that a known issue, or do you want me to create one?

**Comment by michelecocuccio** [comment]
@dmorda you need to give me more info, like which device and brwoser. I am able to swipe on Android. I will try on IOS tomorrow. I am exhausted now :)

**Comment by dmorda** [comment]
Yep, it was iOS and thanks! Now get some rest!
