### ISSUE TITLE
Suggestion: Close on background click

### ISSUE THREAD

**Issue by P4R4DiSi4C** [michelecocuccio/simple-react-lightbox#50]
Hello,

Would it be possible to add the option to close on background click ? I mean, clicking on the background outside the image:

![image](https://user-images.githubusercontent.com/17826095/82362407-98ad4a00-9a0c-11ea-89ae-fa419af97bd9.png)

Thank you very much

**Comment by michelecocuccio** [comment]
@P4R4DiSi4C hello! The functionality it was present but I had to disable it as I had issues when the image was zoomed. I have already fixed it and it's going to be ready for next hot-fix release later on or tomorrow ;)

**Comment by P4R4DiSi4C** [comment]
@michelecocuccio Oh sweet ! Thanks for the good news. I'll be waiting for the hotfix !

**Comment by michelecocuccio** [comment]
@P4R4DiSi4C re-added in version 3.0.2
