### ISSUE TITLE
Disable cursor zoom-in if panzoom disabled

### ISSUE THREAD

**Issue by P4R4DiSi4C** [michelecocuccio/simple-react-lightbox#51]
Hello,

Could you remove the: 
`cursor: zoom-in;`
from SRLImage css class if panzoom is disabled ?

Thank you very much !

**Comment by michelecocuccio** [comment]
@P4R4DiSi4C will do it on the next release

**Comment by michelecocuccio** [comment]
@P4R4DiSi4C this is now fixed in version 3.0.3. 
Thanks
