### ISSUE TITLE
Support for custom JSX in captions

### ISSUE THREAD

**Issue by nielsdos** [michelecocuccio/simple-react-lightbox#52]
Hi

First of all, really amazing library!

My question is if it's possible to allow custom JSX in captions.
The use case I have in mind needs to have labels on images, which I want to display when the image is fullscreen. As well as adding a button unique for each image.
As far as I'm aware, this is only possible with the array declaration?

Thanks in advance

**Comment by michelecocuccio** [comment]
@nielsdos thanks.
I might consider adding this in the near future although this comes with complications, including the fact that you could easily break the style of the light-box if you add too much on the "caption" div. That div is supposed to hold just a snippet of text. Anyway I will consider it for the next release :)

**Comment by michelecocuccio** [comment]
@nielsdos I have added a way to add custom captions. Please read the documentation fully and have a look at the demo [here](https://simple-react-lightbox.dev/with-custom-captions/) 

Thanks :)
