### ISSUE TITLE
Support for rotate Image

### ISSUE THREAD

**Issue by furlanf** [michelecocuccio/simple-react-lightbox#56]
Hi, great work on this library!

What do you think about creating a feature that adds a rotate option?

How can I install and contribute? 

Thanks in advance.

**Comment by netochaves** [comment]
+1

**Comment by michelecocuccio** [comment]
@furlanf hey, thanks!
What do you mean by rotate? Can you please show some examples?

You can contribuite like as any other project. You can fork this repo and add some code and if it's valid I am going to merge it eventually. In regards of installing you just need to clone the repo and do a `yarn run dev` to run the code locally. You will then need to create another folder where you link the package and run some test.
```
  "dependencies": {
    "simple-react-lightbox": "link:..",
  }
```
 
This is how you link a dependency with package.json (in my case I have a folder called "example" inside the simple-react-lightbox main folder, so `link:..` means that it's going back one folder and finding the index.js file for the simple-react-lightbox.

**Comment by furlanf** [comment]
@michelecocuccio 
I mean, a button that can rotate an image by +90deg (or -90deg).
Something like this.

![rotate](https://user-images.githubusercontent.com/4295068/82853841-268da700-9edd-11ea-933c-0ed1f3f6392b.gif)
Thanks for the introduction to installing.
If you don't mind, I would give try to implement this functionality. What do you think?

**Comment by michelecocuccio** [comment]
@furlanf oh, yeah I can add rotation... I don't see why would you need to rotate an image though :) I am thinking about it and I will consider it adding it to the next release, as it's easy to implement it won't pose an issue. 

If you have some time and you feel like you want to try it please do, but as I won't promise I will merge it :) up to you

**Comment by furlanf** [comment]
It would be nice if you could add. I don't found a good library with a rotate option, so I think that it can be a plus.
We use to open images that users sent, something these images were in the wrong position, needing to turn this image.
