### ISSUE TITLE
Setting disableKeyboardControls: true gives TypeError when clicking on images

### ISSUE THREAD

**Issue by hvocalmatic** [michelecocuccio/simple-react-lightbox#57]
**Describe the bug**
I've set disableKeyboardControls: true and couldn't click on other pictures on the carousel anymore. I get the following errors:

TypeError
x.current is not a function

ReferenceError
keyEventHandler is not defined

**Environment*
I've edited the CodeSandbox just to include "disableKeyboardControls: true", you can see the error happen there: https://codesandbox.io/s/simple-react-lightbox-h5zbj?file=/src/components/Gallery.js. Happened to me on Chrome 81.

**To Reproduce**
Click "Open the Lightbox" and try to click on the second image. 
Setting disableKeyboardControls to false fixes the issue.

**Comment by michelecocuccio** [comment]
@hvocalmatic nice catch :) I accidentally remove a condition when i released version 3.0. This is now fixed in 3.0.1! Thanks
