### ISSUE TITLE
Download button not working

### ISSUE THREAD

**Issue by dcanora** [michelecocuccio/simple-react-lightbox#60]
Great work! Very easy to integrate, but having a problem with the Download button.  I'm developing a React website and using material-ui cards to display photos.  The lightbox works great, but the download button doesn't do anything when pressed.

```
<SimpleReactLightbox>
<MuiThemeProvider theme={theme}>
<CssBaseline>
(...)
<Container maxWidth="md">
  <SRLWrapper options={srlOptions}> 
    <Grid container spacing={1}>                       
      {photos && photos.map((image, index) => (
        <Grid item key={index} xs={6} sm={3} md={3}>
          <Card>
            <CardMedia
              component="img"
              alt={alt}
              height="175"
              image={image}
              src={image}                    
              />
          </Card>
        </Grid>
      ))}
    </Grid>
  </SRLWrapper>
</Container>
(...)
</CssBaseline>
</MuiThemeProvider>
</SimpleReactLightbox>
```

I assume it has something to do with using Cards, but can't figure out how to work around. Appreciate any suggestions!

**Comment by michelecocuccio** [comment]
@dcanora hello :)

Chrome has strict CORS rules in regard of downloading images using Javascript. This a known issue and I will try to find a workaround soon but it doesn't entirely depend on me. 
Can you check the console to check if you have any error? Are you using Chrome? Have you tried with another browser?

**Comment by dcanora** [comment]
Hi @michelecocuccio Thanks so much for your quick reply! 

Of course you're right, it's CORS - totally slipped my mind to check. (Same behavior on Chrome, Edge (Chromium) & Safari, btw.) Thanks again.

**Comment by slorber** [comment]
Hi @dcanora , can you please share your solution?

What I see in my case is that the CORS problem appears whenever caching in the fetched URL is enabled. 

Have you tried running the download feature against a CDN (S3/CloudFront...) that has aggressive caching enabled?

This may fix the problem: `fetch(url,{cache: 'no-cache'})`

Note you have a memory leak in that feature, when calling createObjectURL you should revoke it after download completes

**Comment by dcanora** [comment]
Hi @slorber.  Thanks!  In my case, I'm accessing Google Cloud Storage and was able to configure CORS using gsutil.

https://cloud.google.com/storage/docs/configuring-cors

**Comment by slorber** [comment]
We have configured the CDN to serve the appropriate headers, but it seems the fetch request does not send appropriate headers when caching is enabled.

Ie download work only the first time when the fetch request is not cached.
