### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by HuanxinHu** [michelecocuccio/simple-react-lightbox#62]
Great react light box component. 
Can not find type modules when run `npm install @types/simple-react-lightbox`
The solution is ignore ts check when import the module
`// @ts-ignore`
`import SimpleReactLightbox, { SRLWrapper } from 'simple-react-lightbox';`

**Comment by michelecocuccio** [comment]
@HuanxinHu thanks,

yes, unfortunately I am still working on converting everything to TypeScript so it will take a while. Thanks I will do my best to release the new version with support of TypeScript as soon as possible!

**Comment by YahyaBagia** [comment]
@michelecocuccio Thank you for the awesome package. Just keep us informed here on this issue about the typescript availability. Can't wait to try my hands on this. Thank you once again..!!

**Comment by laozhu** [comment]
Before official typing support, you can add below code block to `react-app-env.d.ts` or `next-env.d.ts` file as a workaround.

```typescript
declare module 'simple-react-lightbox' {
  interface SRLWrapperElement {
    src: string;
    caption?: string;
    thumbnail?: string;
    width?: React.ReactText;
    height?: React.ReactText;
    autoplay?: boolean;
    showControls?: boolean;
  }

  interface SRLWrapperProps {
    elements?: SRLWrapperElement[];
    options?: Record<string, any>;
  }

  const SimpleReactLightbox: React.FC;
  const SRLWrapper: React.FC<SRLWrapperProps>;

  export { SRLWrapper };
  export default SimpleReactLightbox;
}
```

**Comment by guilhermefront** [comment]
Here's a PR for adding @types/simple-react-lightbox

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54124
