### ISSUE TITLE
Full size images are used as thumbnails

### ISSUE THREAD

**Issue by albertgasset** [michelecocuccio/simple-react-lightbox#65]
**Describe the bug**
When using images wrapped in links, the lightbox uses the images referenced by the links as thumbnails. 

**Environment**
I'm using NextJS and latest version of Chrome and Firefox. The bug is also present in the demo site: https://simple-react-lightbox.dev/with-thumbs/

**To Reproduce**
1. Go to https://simple-react-lightbox.dev/with-thumbs/
2. Check the DOM the first image in the grid. The image src is https://www.simple-react-lightbox.dev/docs/gallery/thumbnails/unsplash17.jpg and the link href is https://www.simple-react-lightbox.dev/docs/gallery/unsplash17.jpg
3. Click on the image to open the lightbox.
4.  Check the DOM of the first thumbnail. The "background-image" property of the inline style points to https://www.simple-react-lightbox.dev/docs/gallery/unsplash17.jpg (the full size image). 

**Additional context**
I've tracked the bug to this line of the code:
https://github.com/michelecocuccio/simple-react-lightbox/blob/master/src/SRL/SRLWrapper/index.js#L213 (the same url is assigned to "thumbnail" and "source").

**Comment by michelecocuccio** [comment]
@albertgasset thanks, this is fixed now in 3.2.3-2
