### ISSUE TITLE
Request: support for video and other content?

### ISSUE THREAD

**Issue by JeffMusgrave** [michelecocuccio/simple-react-lightbox#66]
I was thinking it would be a pretty complete system if we could get support for video, eg: click on a thumbnail and the lightbox opens up to an overlaid youtube video or local video via a video tag. Likewise other embeds like soundcloud or local audio tags would be nice to add!

**Comment by michelecocuccio** [comment]
@JeffMusgrave Thanks for the suggestion. I will implement this in the near future. 
It takes time to add video support and other media files but it's definitely in the work.

**Comment by michelecocuccio** [comment]
@JeffMusgrave this will be implemented on the next release, but is going to be on a PRO version. I have put a lot of work on this and I am working alone on this project. The PRO version will contains some new features including the possibility to change the icons. Some of the features will be removed from the free version unfortunately. Don't worry though. The PRO version will be really cheap.
