### ISSUE TITLE
Memory leak and different galleries

### ISSUE THREAD

**Issue by AndrewJavaScript** [michelecocuccio/simple-react-lightbox#67]
Hello! I have a question and error. My question is - how i can make 3 different galleries in one page? Maybe SRLWrapper can have **id** or something, so it will not add all images at one page in one gallery? And this is error in  SRLWrapper:
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in bound  (at Puppies.jsx:19)
    in bound  (created by bound )
    in bound  (at Puppies.jsx:18)
    in div (at Puppies.jsx:17)
    in Puppies (at App.js:37)

I'm new in React and this is my code:
```
import React from 'react';
import './Puppies.css';
import SimpleReactLightbox, { SRLWrapper } from "simple-react-lightbox";

const Puppies = (props) => {
    const puppies = props.puppies.map((el, i) => {
        if (!props.puppies) return null;
        return <div key={i} className='mb-5'>
            <div className='mb-3'>{el[0].alt}</div>
            {el.map((img, index) => {
                if (index === 0) return <img key={index} src={img.src} alt={img.alt} className='img-with-pointer'/>;
                return <img key={index} src={img.src} hidden alt={img.alt} />
            })}
        </div>;
    });
    return (
        <div className="puppies">
            <SimpleReactLightbox>
                <SRLWrapper>
                    {puppies}
                </SRLWrapper>
            </SimpleReactLightbox>
        </div>
    );
};

export default Puppies;
```
I got data from JSON file. No any queries to server.

**Comment by michelecocuccio** [comment]
@AndrewJavaScript hey Andrew,

There is no error with the light-box. The error is caused by the way you are writing your code. "puppies" is null on render and that causes an error in your app. I quickly created a [CodeSandobx](https://codesandbox.io/s/upbeat-fast-9bdjk?file=/src/App.js) demo to see how I fixed the code on line 7. 

In order to have more than one light-box in one page you need to have multiple `<SimpleReactLightbox/>` components like this: 

`<SimpleReactLightbox>
  <SRLWrapper>
     Gallery 1
  <SRLWrapper/>
<SimpleReactLightbox/>

<SimpleReactLightbox>
  <SRLWrapper>
     Gallery 2
  <SRLWrapper/>
<SimpleReactLightbox/>

<SimpleReactLightbox>
  <SRLWrapper>
     Gallery 3
  <SRLWrapper/>
<SimpleReactLightbox/>

`

**Comment by AndrewJavaScript** [comment]
Michele, please check your link to CodeSandobx. I checked code 10 times but didnt find any difference. Thank you for your help.

**Comment by michelecocuccio** [comment]
@AndrewJavaScript, line 7 :) 

`const puppies = props.puppies?.map((el, i) => {}`

the question mark is a short syntax to check if the variables exist, if not is going to be set it to undefined. This is advanced JavaScript, you can write the standard way too.

**Comment by AndrewJavaScript** [comment]
I delete return null, use your short syntax, but still have error, when i change pages. My code is simple. Repository with my project https://github.com/AndrewJavaScript/JS_Homework/tree/master/pitomnik_react

**Comment by michelecocuccio** [comment]
@AndrewJavaScript your code is running fine, don't know what to say. Look at the [video](https://drive.google.com/file/d/1WIPMds1XbkfQcU3FdDSWzu-GDtKGRMxm/view) that I have recorded. I just run your repo and start it, I haven't changed anything. Sorry, I can't help if you are having issues with your code but for me everything works fine and there is no issue with the light-box.

**Comment by AndrewJavaScript** [comment]
Man, you are great, if you trying to help me even with installing my repo and making videos. My app dont crush, you need to open console and check this problem there. You click enough to get that error. I need to learn how to make videos too.

**Comment by AndrewJavaScript** [comment]
I made video also with that error. Please tell me if my link is ok https://drive.google.com/file/d/18a6NpTY1valM3d6kB8BVRDGF89049Q7R/view?usp=sharing

**Comment by michelecocuccio** [comment]
@AndrewJavaScript I have requested access to the video. Anyway I don't have anything in the "console" log. I will watch the video later and I love to help but unfortunately I don't have much time to offer individual help. I helped as much as I could. I will come back after I watch the video.

**Comment by AndrewJavaScript** [comment]
I update acces for the same link https://drive.google.com/file/d/18a6NpTY1valM3d6kB8BVRDGF89049Q7R/view?usp=sharing

**Comment by michelecocuccio** [comment]
@AndrewJavaScript I can see the issue but I don't see what's wrong. Anyway that's a warning and not an error. I will have a look but I think this has something to do with your App and the router and not the light-box itself. Unfortunately I can't offer individual help or code reviews. I will investigate the issue but I can't see that error on my [example website](https://simple-react-lightbox.dev) which also uses router.

**Comment by zcmgyu** [comment]
Same issue here
