### ISSUE TITLE
Question: possible to get the image to fill the lightbox?

### ISSUE THREAD

**Issue by gortron** [michelecocuccio/simple-react-lightbox#68]
In the options section of the README.md, you show two sample images: one of a motorcycle, and one of a mountain lake. The mountain lake image seems to fill the `SRLStage` / `SRLLightbox` component, with buttons resting on top of the image. I think this looks _brilliant_, and was wondering which specific options you used to configure the Lightbox to appear that way? Or if that was a piece of custom CSS for those components?

Thanks for any guidance, here.

**Comment by michelecocuccio** [comment]
@gortron hello :) thanks for asking.

That's just the imaged zoomed-in with the panz-zoom functionality. But I might consider adding this as feature in the near future! I also think with a bit of Javascript and CSS customisation you could achieve the same thing, especially using the provided callbacks.

**Comment by gortron** [comment]
Thanks Michele. I'll let you know if I accomplish this with JS/CSS. 

(Well done on the component, by the way!)
