### ISSUE TITLE
useLightbox() hook does not work with multiple SRLs on a single page

### ISSUE THREAD

**Issue by Blobson** [michelecocuccio/simple-react-lightbox#69]
**Describe the bug**
I have several images on a page each opening a separate gallery in an SRL. I have setup multiple `SRLWrapper` objects with different lists of images provided via `images` prop and tried to use `useLightbox()` hook to open SRL but it is always showing the same list of images from the 1st `SRLWrapper` on a page. 

**To Reproduce**
1. Setup two `SRLWrapper` objects with different lists of images for each of them.
2. Try using `useLightbox()` hook to open the SRL popup.

**Comment by michelecocuccio** [comment]
@Blobson hello. If you want multiple light-box on a single page you need to wrap each one in their own `<SimpleReactLightbox>` component like this

`
<SimpleReactLightbox>
  <SRLWrapper>
     Gallery 1
  <SRLWrapper/>
<SimpleReactLightbox/>

<SimpleReactLightbox>
  <SRLWrapper>
     Gallery 2
  <SRLWrapper/>
<SimpleReactLightbox/>

<SimpleReactLightbox>
  <SRLWrapper>
     Gallery 3
  <SRLWrapper/>
<SimpleReactLightbox/>
`

this is written in the documentation. 

Thanks

**Comment by Blobson** [comment]
Tried without luck. The issue still persist. 
Maybe it's because I am using images prop:
```
const Gallery = ({ icon, images }) => {
  const { openLightbox() } = useLightbox()
  return (
    <SimpleReactLightbox>
      <SRLWrapper images={images} />
      <img src={icon} onClick={() => openLightbox()} />
    <SimpleReactLightbox/>
  )
}
```
and here is how I use it:
```
<Gallery icon="icon1.jpg" images={gallery1} />
<Gallery icon="icon2.jpg" images={gallery2} />
<Gallery icon="icon3.jpg" images={gallery3} />
```
and here is the error:
```
Uncaught TypeError: n.dispatch is not a function
    at openLightbox (index.es.js:22)
    ...
```

**Comment by Blobson** [comment]
Found a workaround:
```
const GalleryBox = ({ icon, images }) => {
  const { openLightbox() } = useLightbox()
  return (
    <>
      <SRLWrapper images={images} />
      <img src={icon} onClick={() => openLightbox()} />
    </>
  )
}

const Gallery = (props) => (
  <SimpleReactLightbox>
    <GalleryBox {...props} />
  </SimpleReactLightbox>
)
```

**Comment by michelecocuccio** [comment]
@Blobson it should be
`const { openLightbox } = useLightbox()`

(don't need the "()")

**Comment by Blobson** [comment]
Sure it's just a typo in my example. It does not appear in real code.

**Comment by Blobson** [comment]
It works after I've applied the workaround, to bring hook inside `SimpleReactLightbox` context.
But now I see warnings:
```
Warning: Encountered two children with the same key, ``. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

**Comment by michelecocuccio** [comment]
@Blobson this is not related to the light-box itself. Are you adding different keys to all of your images? Each image must have a unique key. This a generic React message that enforce the rule to adding a unique key especially when looping through an array or an object. Please read more [here](https://reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys) :)
