### ISSUE TITLE
Prop for controlling opening speed

### ISSUE THREAD

**Issue by LeunensMichiel** [michelecocuccio/simple-react-lightbox#7]
Hi! This looks like a very promising lightbox. Tested it and looks good. The one thing missing for me is a prop for controlling the speed when clicking on an image. Only the speed between images is configurable right now. But I'd like the lightbox to "pop-up" a bit faster.

Again, great work!

**Comment by michelecocuccio** [comment]
Hello!
Thank you very much for your feedback! I think that's will be my next implementation. So you mean the speed of the opening of the light-box itself?

**Comment by LeunensMichiel** [comment]
Yes, correct!

**Comment by michelecocuccio** [comment]
Added on Version 2.0 with the option ```transitionSpeed```
