### ISSUE TITLE
Strange behavior on iOS (while zoomed in)

### ISSUE THREAD

**Issue by ssazero** [michelecocuccio/simple-react-lightbox#70]
Hello, I used your simple-react-lightbox in my last project and it's awesome! Unfortunately, I found a really strange behavior after zooming in and moving images in iOS devices. 
While moving the image it stutters and crashes.

I'm using the latest Gatsby version, but I've tested your live demo on my iPhone XS and iPad 10.2 and I encountered the same problem.

1. Click any image
2. Zoom in
3. Touch the image and move it in any direction
4. Here comes the problem ^ - image stutters

**Comment by michelecocuccio** [comment]
@ssazero thanks. I am aware of this issue. I will fix it on the next release. I am currently on holiday so it might take couple of weeks but it's already on my list.
