### ISSUE TITLE
costrolls missing in fullscreen

### ISSUE THREAD

**Issue by muscaiu** [michelecocuccio/simple-react-lightbox#71]
Hello, first of all great job with this library, i love it!
I wanted to implement it in our project, but i found and issue.

The controls dissaprear on fullscreen and instead there is a plus sign that behaves weird.

![2020-07-22_16-43-23](https://user-images.githubusercontent.com/11426309/88183789-93ea5980-cc3a-11ea-8ab9-45a5558bf477.png)

Is this a known issue? I couldn't find anything related to it here.

So i can't yet recommend to use this library until this issue is fixed.

Thanks.

**Comment by michelecocuccio** [comment]
@muscaiu this is not a bug. This is how fullscreen works in any given browser whenever is implemented using the [Javascript full screen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API). This is to display an image without distraction. In the case of a video you will have controls coming from the video itself. Image has no control. Thanks

**Comment by muscaiu** [comment]
Hey, @michelecocuccio  if you look at this library demo https://fslightbox.com/react , the controls are still available in the fullscreen mode. Any plans of adding it to this library soon?

**Comment by michelecocuccio** [comment]
@muscaiu I will see what I can do on the next release :)

**Comment by michelecocuccio** [comment]
@muscaiu full screen has been improved and control added in version 3.3 and above.
Thanks
