### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by muriloneo** [michelecocuccio/simple-react-lightbox#72]
**Describe the bug**
When I try to download image I get this error: `index.es.js:31 Uncaught ReferenceError: regeneratorRuntime is not defined`

**Environment*
ReactJs

**To Reproduce**
1. install
2. Create a wrapper with images
3. Click image
4. Click download button

**Screenshots**
![image](https://user-images.githubusercontent.com/16191560/88292345-e7f34d80-cccf-11ea-90b3-8ec2c49f2712.png)

**Comment by michelecocuccio** [comment]
@muriloneo hello! Are you using Babel? I can't reproduce this error in any environment. This error seems related to Babel. Can you let me know which version of React and Create React App are you using? Are you using Gatsby or NextJS? Please specify better the environment so I can reproduce the issue. Thanks

**Comment by muriloneo** [comment]
Yes. I am using babel:

"react": "16.9.0",
"@babel/runtime": "7.0.0",
"@babel/core": "7.0.0",
"@babel/plugin-proposal-class-properties": "7.2.1",
"@babel/plugin-proposal-decorators": "7.2.2",
"@babel/plugin-proposal-do-expressions": "7.0.0",
"@babel/plugin-proposal-export-default-from": "7.0.0",
"@babel/plugin-proposal-export-namespace-from": "7.0.0",
"@babel/plugin-proposal-function-sent": "7.0.0",
"@babel/plugin-proposal-json-strings": "7.0.0",
"@babel/plugin-proposal-logical-assignment-operators": "7.0.0",
"@babel/plugin-proposal-nullish-coalescing-operator": "7.0.0",
"@babel/plugin-proposal-numeric-separator": "7.0.0",
"@babel/plugin-proposal-optional-chaining": "7.0.0",
"@babel/plugin-proposal-pipeline-operator": "7.0.0",
"@babel/plugin-proposal-throw-expressions": "7.0.0",
"@babel/plugin-syntax-dynamic-import": "7.2.0",
"@babel/plugin-syntax-import-meta": "7.0.0",
"@babel/plugin-transform-runtime": "7.0.0",
"@babel/polyfill": "7.0.0",
"@babel/preset-env": "7.2.0",
"@babel/preset-flow": "7.0.0",
"@babel/preset-react": "7.0.0",
"@babel/preset-stage-1": "7.0.0",
