### ISSUE TITLE
Redirect while all images not loaded fully

### ISSUE THREAD

**Issue by Gid733** [michelecocuccio/simple-react-lightbox#73]
**Describe the bug**
Bug happens when there're a lot of pictures to be loaded. Basically, when there're like 100 pictures and thumbnails to be loaded - on thumbnail click gallery reroute you to a route that doesn't exists and not opening a lightbox.

**Environment**
Latest version of CRA, React 16.13.1, Node 12.16.2, Chrome 84.0.4147.89

**To Reproduce**
1. Create basic CRA app.
2. Add page with 100 images and <a> tag to the dedicated URL (any available site with images)
3. Click on any thumbnail.
4. Lightbox doesn't open, instead route changes to the one that's declared in the full image path
5. If to wait long enough until all images are loaded - lightbox would be opened normally.

**Screenshots**
Path in the browser
![image](https://user-images.githubusercontent.com/9092606/88306627-a4223780-cd13-11ea-9a60-ca16605e641c.png)
Code used
![image](https://user-images.githubusercontent.com/9092606/88307030-1f83e900-cd14-11ea-9f16-e52832e49968.png)

**Additional Info**
I'm using Redux and load like 100 objects to it with image hash strings, after that images are rendered according route in the application.

**Comment by michelecocuccio** [comment]
@Gid733 can I see a more complete example? Have you wrapped your code correctly in the `<SimpleReactLightbox>` component and `<SRLWrapper>` component? I think the problem in your case is that you have a function as "href"... I will need to test a similar case as nothing like this ever happened to me before. Are you able to reproduce your example in a sandbox?

**Comment by Gid733** [comment]
Yes, I've wrapped it this way. Some more screenshots for you. I'm pretty sure it happens because of <a> tag. But the strange thing it's fully working if I would wait till all thumbnails are here. I would try to reproduce it in the sandbox for you later today or tomorrow.
![image](https://user-images.githubusercontent.com/9092606/88309253-b6ea3b80-cd16-11ea-9e26-c4f5752efbc2.png)
![image](https://user-images.githubusercontent.com/9092606/88309311-cec1bf80-cd16-11ea-8ad5-2b18d562797f.png)
![image](https://user-images.githubusercontent.com/9092606/88309407-f1ec6f00-cd16-11ea-9a65-9d46b035492a.png)

**Comment by michelecocuccio** [comment]
Thanks. In the meantime I will do some testing on my own. I have an image loaded check to see if all the images are loaded. Sorry I am currently on holiday i will try to do my best to fix it when I am back.

**Comment by Gid733** [comment]
@michelecocuccio successfully reproduced on code sandbox. Just open it and click fast on any thumbnail you see - it would be opened in separate page, not in lightbox.
https://codesandbox.io/s/bug-with-click-on-not-loaded-thumbnails-qitqk

**Comment by michelecocuccio** [comment]
@Gid733 thanks. I can see the issue. I will check what I can do to fix that when I am back as I maybe have an idea. Although I think loading 400 images is not really a good practice anyway.

**Comment by Gid733** [comment]
@michelecocuccio thanks. 400 images is just to reproduce the issue, since I could not find a free API that would be capable to give images from something like S3, I'm loading like 20 at once to make a preview for screenshots, but since server is not very powerful it takes some time to load them all, since they are pulled from S3 storage with a low connection for some users. Basically if you have any connection like client -> server -> dedicated storage - you might get this result on a slow internet speed.

**Comment by michelecocuccio** [comment]
@Gid733 You are absolutely correct. I will try to understand why my imageloaded validation is not working. Thanks for pointing out this issue.

**Comment by muriloneo** [comment]
I just have a similar issue. My images are getting a delay to correct load from S3 (using S3Image) and the lightbox opens a 1x1 image. If I reload the page the image is cached and it shows fine.

**Comment by michelecocuccio** [comment]
@Gid733  this should be fixed in version 3.3.0 and above.
Please make sure to update to the latest version.
