### ISSUE TITLE
Getting error while using SRL with Next.Js 

### ISSUE THREAD

**Issue by rustamveer** [michelecocuccio/simple-react-lightbox#74]
Hi

I have a website in Reactjs and now I am moving it to NextJS. However, I am getting an error when I used the Simple React lightbox. Basically, I wrapped the images between <SRLWrapper>

I render things on ServerSide using Appollo. This package works perfectly with plain Reactjs app

### Error:
Unhandled Runtime Error
TypeError: p.dispatch is not a function

Call Stack
<unknown>
node_modules\simple-react-lightbox\dist\index.es.js (7:4642)
n
/_next/static/development/pages/gallery.js (23246:5127)
<unknown>
node_modules\simple-react-lightbox\dist\index.es.js (7:5737)
a.<anonymous>
/_next/static/development/pages/gallery.js (23246:7131)
a.push../node_modules/simple-react-lightbox/dist/index.es.js.n.emitEvent
node_modules\simple-react-lightbox\dist\index.es.js (1:6403)
a.push../node_modules/simple-react-lightbox/dist/index.es.js.a.complete
/_next/static/development/pages/gallery.js (23246:2470)
a.push../node_modules/simple-react-lightbox/dist/index.es.js.a.progress
node_modules\simple-react-lightbox\dist\index.es.js (7:2057)
<unknown>
/_next/static/development/pages/gallery.js (23246:1855)

### Environment and Packages which my app is using:
{
  "name": "react-graphql-d",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "proxy": "http://localhost:3000",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@apollo/react-hooks": "^3.1.5",
    "@apollo/react-ssr": "^3.1.5",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link-http": "^1.5.17",
    "graphql": "^15.3.0",
    "graphql-tag": "^2.10.4",
    "isomorphic-unfetch": "^3.0.0",
    "next": "^9.4.4",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "simple-react-lightbox": "^3.2.3-3"
  }
}

Thank you!

**Comment by michelecocuccio** [comment]
@rustamveer I can't see your code but I assume you have wrapped everything in the `<SimpleReactLightbox>` first and then `<SRLWrapper>` right? You haven't mentioned `<SimpleReactLightbox>` in your comment so I believe you forgot.

In nextJS you can use the "_app.js" file and something like this.

So you will do something like:

```
    <ApolloProvider client={apolloClient}>
      <SimpleReactLightbox>
          <Component {...pageProps} router={router} />
      </SimpleReactLightbox>
    </ApolloProvider>

```
and then in any of your page you can use the `<SRLWrapper>` component with the images as per the documentation.

**Comment by rustamveer** [comment]
@michelecocuccio  Yeah, you are right. It is my mistake, Sorry. I missed adding <SimpleReactLightbox >. 
It works flawlessly with Next.js too 

Thank you
