### ISSUE TITLE
Is there a way i can give a fallback image if my image/thumbnail is breaking 

### ISSUE THREAD

**Issue by supreet-js-logger** [michelecocuccio/simple-react-lightbox#75]
**Describe the bug**
I get images from third party and those images may or may not work some time. I want to give a fallback image in such scenario.

**To Reproduce**
Please include steps to reproduce the behaviour:
1. Pass an invalid image in the gallery
2. I see a broken image in the lightbox.
3. I show image lightbox on click of button and have passed images using props as an array as i want to load lightbox on click of a button and dont want to load/show images before hand.

**Additional context**

**Comment by michelecocuccio** [comment]
@supreet-js-logger thanks for the question (please next time select "question" and not "bug" as this is not a bug).

In regards of your question, I think that's out of the scope of the Simple React Lightbox. You could instead use JavaScript to detect images that are not loading or that are returning a 404 and replace them with something else. The Simple React Lightbox only takes care of the light-box functionality. It doesn't manipulate the images in any way.
