### ISSUE TITLE
Request: Support i18n?

### ISSUE THREAD

**Issue by qwIvan** [michelecocuccio/simple-react-lightbox#77]

**Comment by michelecocuccio** [comment]
@qwIvan please refrain to open something as a bug if is not :)

Thanks. I will add supporto for i18n on the next release probably.

**Comment by michelecocuccio** [comment]
@qwIvan this has ben added in version 3.3.0 and above.
I have added the possibility to add custom text for the buttons and therefore you can now translate the buttons.
