### ISSUE TITLE
Make download button lead to a different link?

### ISSUE THREAD

**Issue by kyleawayan** [michelecocuccio/simple-react-lightbox#82]
I'm using this with [react-photo-gallery](https://github.com/neptunian/react-photo-gallery) and I was wondering if there's a way to redirect to another link with the download button.

```
const photos = [
  {
    src: "../pictures/baf/previews/IMG_2457_DxO.jpg",
    width: 3 ,
    height: 2 ,
    download: "../pictures/baf/IMG_2457_DxO.jpg",
    },
```

I have a low-res picture as `src` for the main picture that shows on the webpage, for faster loading time. Is there a way to redirect to the full-res picture when someone clicks the download button? Like if I put a `download` link in my array?

**Comment by michelecocuccio** [comment]
@kyleawayan not really. The download button downloads the current image. I think is counter intuitive to download something else. I will think to maybe add custom "link" for the download button in the near future maybe improving the whole functionality but not for now. Sorry :(

**Comment by felipenmoura** [comment]
I was looking for a way to have a link that will download the image with a specific name and I couldn't find a way to specify the filename and extension in the documentation.
It's name is always `download` and if the image is in a `webp` format, it does not add the extension!

**Comment by michelecocuccio** [comment]
@felipenmoura hello.

I can have a look at this. I should be able to change the "download" name when downloading an image. In regards of using a custom name I am not sure this will be an option but I will have a look.

**Comment by felipenmoura** [comment]
Thanks @michelecocuccio 
Also...I noticed .webp images are downloaded without the extension, becoming "invalid" files. For us, devs, it's ok, but for regular people, it's complicated to ask them to add the extension after downloading the file, you know.

Thanks for the attention 😊
