### ISSUE TITLE
Not Working with Gatsby 2.24.26

### ISSUE THREAD

**Issue by dvreed77** [michelecocuccio/simple-react-lightbox#83]
**Describe the bug**
SRL Doesn't render Gatsby Images using <Img>, but does render plain <img>.

Reference code below, my Gatsby page renders all Images, but only the placekitten image is clickable and will render in slideshow.

**Environment**
Gatsby 2.24.26
simple-react-lightbox 3.3.3 

**To Reproduce**
- Wrap page in gatsby-browser.js with SimpleReactLightbox
- Wrap images in Gatsby page with SRLWrapper

**Additional context**
```javascript
//gatsby-browser.js
export const wrapRootElement = ({ element }) => {
  return <SimpleReactLightbox>{element}</SimpleReactLightbox>;
};

```
```javascript
// pages/paintings.tsx
<SRLWrapper>
  <img src="https://placekitten.com/g/200/300" alt="" />
  {paintings.map((painting) => (
    <Img
      key={painting.node.id}
      fluid={painting.node.frontmatter.image.childImageSharp.fluid}
    />
  ))}
</SRLWrapper>
```

**Comment by dvreed77** [comment]
I saw issue #11, but it seems like this still isn't working

**Comment by michelecocuccio** [comment]
@dvreed77 it's likely I have introduced this bug with the last fixes. I will fix it as soon as possible, thanks.

**Comment by michelecocuccio** [comment]
@dvreed77 I have just added a fix in v3.3.4.
Can you give it a go? Also it will be awesome if you could replicate your project to a CodeSandbox or if it's public if you could give me the link to the repo so I can fork it. I don't have much time right now but I need to find a Gatsby theme that loops through images (like yours). Or if you know a pre-made theme like this let me know. I need to do a lot of testings with Gatsby Images. Thanks

**Comment by dvreed77** [comment]
@michelecocuccio let me figure out a way to get a demo of Gatsby on CodeSandbox, would love to contribute something if I can.

**Comment by michelecocuccio** [comment]
@dvreed77 thanks, no rush! :)

**Comment by dvreed77** [comment]
@michelecocuccio I shared a sandbox with you. Gatsby seems a little flaky with CodeSandbox, but it works!! Thanks for the help

**Comment by michelecocuccio** [comment]
@dvreed77 thank you very much. Where did you shared that?

**Comment by dvreed77** [comment]
@michelecocuccio here is the link. I figured you would get an email or something.

https://codesandbox.io/s/crazy-kare-8wik5?file=/src/pages/index.js

**Comment by michelecocuccio** [comment]
@dvreed77 thanks a lot :) I have tweaked your example a bit and I have created mine (you were using "allImageSharp" query, I am using "allFile" query so you can select the images that you want from a specific folder. I have added the example folder to the repository so that it can help anyone using Simple React Lightbox with Gatsby and gatsby-images.

Thanks again 👍
