### ISSUE TITLE
Add custom button in srl

### ISSUE THREAD

**Issue by AkshayToraskar** [michelecocuccio/simple-react-lightbox#85]
is it possible to add custom button with custom events in SRL, like delete image

**Comment by michelecocuccio** [comment]
@AkshayToraskar hello. 

Thanks for asking. 
Unfortunately, I think this will be out of the scope of Simple React Lightbox. You can delete the image using simple JavaScript code I guess :) 

Thanks again!

**Comment by AkshayToraskar** [comment]
i was planning to add button inside lightbox, is there any way that makes possible with javascript if possible please suggest some demo
