### ISSUE TITLE
openLightbox throws n.dispatch is not function in Nextjs

### ISSUE THREAD

**Issue by AwrminKhodaei** [michelecocuccio/simple-react-lightbox#87]
**Describe the bug**
im using light-box with nextjs v9.4.1. everything works very well unless i call openLightbox function to open light box from a custom button 

**Environment*
NextJS 9.4.1

**Comment by AwrminKhodaei** [comment]
I'm destructuring like this:
`import { useLightbox } from "simple-react-lightbox";`
` const { openLightbox } = useLightbox();`
and calling function like this:
`<Button onClick={() => openLightbox()} >Open Light Box</Button>`

**Comment by michelecocuccio** [comment]
@AwrminKhodaei have you wrapped your app with your` <SimpleReactLightbox>` component? Is difficult to understand what's your issue. I am sure it's about the way you are composing your app. The function must be called from a Component nested in the ` <SimpleReactLightbox>` component. Please let me know, I am sure that's the issue.

**Comment by AwrminKhodaei** [comment]
> @AwrminKhodaei have you wrapped your app with your` <SimpleReactLightbox>` component? Is difficult to understand what's your issue. I am sure it's about the way you are composing your app. The function must be called from a Component nested in the ` <SimpleReactLightbox>` component. Please let me know, I am sure that's the issue.

@michelecocuccio i found the problem. previously `<SimpleReactLightbox/>` was wrapped in my page but i changed it to wrapp whole app in _app.js file and problem solved.
