### ISSUE TITLE
[Feature Request] Need to custom event to SRL

### ISSUE THREAD

**Issue by lyquocnam** [michelecocuccio/simple-react-lightbox#88]
dear author,
I need to disable open lightbox when click image in SRL component and do it manually.
How to do that ?

**Comment by michelecocuccio** [comment]
@lyquocnam hello :) 
So you wan't to close the light-box when clicking on an image in an opened light-box? In terms of UX/UI this is not ideal, because when you click on the image there is the panzoom functionality kicking in. Is this what you mean?

**Comment by lyquocnam** [comment]
> @lyquocnam hello :)
> So you wan't to close the light-box when clicking on an image in an opened light-box? In terms of UX/UI this is not ideal, because when you click on the image there is the panzoom functionality kicking in. Is this what you mean?

Hello @michelecocuccio :)
```
<SRLWrapper>
          <img src="src/for/the/thumbnail/image.jpg" alt="Umbrella" onClick={dosomething} />
          <img src="src/for/the/thumbnail/image_two.jpg" alt="Whatever" onClick={dosomething} />
      </SRLWrapper>
```
default when click to an image, lightbox will be show. so i want disable this action. Because i have another behavior and show lightbox after that.
thank you !

**Comment by michelecocuccio** [comment]
@lyquocnam sorry is not possible and it doesn't make sense to be completely honest. 

If you want to exclude some images from the light-box simply don't wrap them around the `<SRLWrapper />` component. If you want to use the light-box and do something with the image you can use this approach [https://simple-react-lightbox.dev/with-images-as-prop/](https://simple-react-lightbox.dev/with-images-as-prop/) which I think it's the perfect solution in your case 👍
