### ISSUE TITLE
Full Screen don't work on iPad devices

### ISSUE THREAD

**Issue by Matti93GL** [michelecocuccio/simple-react-lightbox#89]
**Describe the bug**
Full Screen don't work on iPad devices.

**To Reproduce**
Please include steps to reproduce the behaviour:
1. Open the Image Gallery
2. Click on Full Screen Button
3. The full screen don't work, nothing is happend

**Additional context**
This only happend on iPad devices
<img width="980" alt="ipaderror" src="https://user-images.githubusercontent.com/62907714/94313044-654b7080-ff54-11ea-810e-1c49e889d593.png">
![issue](https://user-images.githubusercontent.com/62907714/94314740-8bbedb00-ff57-11ea-8266-72a24e3d194e.gif)

**Comment by michelecocuccio** [comment]
@Matti93GL thanks.
Apparently the returned promise doesn't work in Safari. As I am working on a big release, I will just release a quick fix in the next few days. Nice catch, thank you very much.

**Comment by Matti93GL** [comment]
Hi @michelecocuccio thanks for the update ! i will wait that fix ! :) Thank you !

**Comment by Matti93GL** [comment]
@michelecocuccio if you see the gif, you can see that the panzoom is not working correclty ! I see a bug is closed about that but i think is not working fine yet

**Comment by michelecocuccio** [comment]
@Matti93GL what's is not working fine? What device are you using? What OS are you using? I don't see anything related to panzoom on the GIF. Also please let's leave this issue focused on the fullscreen functionality. Thanks
