### ISSUE TITLE
 Support in showing / hiding all controls

### ISSUE THREAD

**Issue by SaliMike** [michelecocuccio/simple-react-lightbox#9]
It would be useful to support showing / hiding fullscreen button (showFullscreen) and autoplay button (showAutoplay). When they are not needed. Currently they cannot be turned off.

**Comment by michelecocuccio** [comment]
Hello @SaliMike. Thanks for your feedback!

Autoplay can be hidden if you set the value to be 0. As per the documentation: "Set it to 0 if you don't want to use the auto play functionality and hide the button". Regarding hiding the full-screen button I will do it on the next release. 

Thanks
