### ISSUE TITLE
crashes when ever the images are not fully loaded

### ISSUE THREAD

**Issue by alisayed95** [michelecocuccio/simple-react-lightbox#90]
when I call the photos from the server it's crashes and when it's cached everything works fine
could you help me please??

**Comment by michelecocuccio** [comment]
@alisayed95 Sorry, you need to be more specific than this.

What crash? What happens? What's the error? How are you loading the images? You shouldn't be able to click on the images when the light-box is loading. Which version are you using? Where does the issue happen? Can you provide a CodePen example ora share the code you are using.

Without any information, I can't give much help I am afraid.

**Comment by alisayed95** [comment]
when ever I click to the button that have a group of images it crash when all of the images aren't fully loaded, but when it's fully loaded and cached everything is okay

**Comment by michelecocuccio** [comment]
@alisayed95 sorry is still not clear. You mean a button to open the light-box? Using the hook? What's the error. You need to show me exactly what's going on or I won't be able to help you.
