### ISSUE TITLE
Image as background

### ISSUE THREAD

**Issue by JulienHe** [michelecocuccio/simple-react-lightbox#93]
Hello,

Thanks for the hard work and the amazing project!
I was wondering if it will be possible to actually have a picture as background?
![image](https://user-images.githubusercontent.com/718868/95702051-2fadc380-0c86-11eb-9393-7ac7065d5316.png)
Something like this.

Thank you!

**Comment by michelecocuccio** [comment]
@JulienHe hello.

It will be soon. I am working on a new release which support this feature.
Eventually you can target the body and the class `SRLOpened` to override the background with plain CSS for now.

Thanks
