### ISSUE TITLE
Is it suitable for implementing a Instagram style lightbox?

### ISSUE THREAD

**Issue by stonesthatwhisper** [michelecocuccio/simple-react-lightbox#94]
By instagram-style, I mean having an image and an info+chat in two columns. Is this outside of the scope for this project? Thx.

<img width="1155" alt="Screen Shot 2020-10-13 at 12 04 45 PM" src="https://user-images.githubusercontent.com/6599254/95904464-69490200-0d4c-11eb-89d7-b3ef0c8f96ea.png">

**Comment by michelecocuccio** [comment]
@stonesthatwhisper this is out of the scope of this project. Sorry.
Thanks for asking
