### ISSUE TITLE
SRL state elements not updating to the latest image with images as a prop

### ISSUE THREAD

**Issue by endrureza** [michelecocuccio/simple-react-lightbox#96]
**Describe the bug**
I navigate between two links which fetching new images, and using the images as prop with SRLWrapper

```
const Gallery = ({ images = [] }) => {
  const [lightboxImages, setLightboxImages] = useState(null)

  useEffect(() => {
    if (images) {
      setLightboxImages(
        images.map((img) => ({
          src: img.url,
          thumbnail: img.thumbnail,
          caption: img.caption
        }))
      );
    }

    return () => {
      setLightboxImages(null);
    };
  }, [images]);

  return (
    <>
      <SRLWrapper images={lightboxImages} />
      <a onClick={() => openLightbox()}>Open Gallery</a>
    </>
  );
};
```

everytime i click open gallery, the images don't change. it keeps showing the first group images that been loaded. i check the elements state, it doesn't change either. and why elements state not grabbing the fresh images ?

**Environment**
Next.js 9.5.2
Node v14.6.0
React 16.13.1
Chrome 86.0.4240.80

**Comment by michelecocuccio** [comment]
@endrureza hello.

Can you please reproduce your example on CodeSandbox? I can't reproduce your issue but I don't understand how are you fetching the images? Are you fetching them asynchronously and then passing them as props? A more complete example would be better. I have fetched images before and set them with the state and everything works normally. Maybe there is an issue with your useEffect? Have you checked that you are getting the new images in the useEffect?

**Comment by endrureza** [comment]
Whoa, never mind. apparently, it's because i don't add key attribute into SRLWrapper, it causes the component to render the same SRLWrapper instead render the new one with new images.

**Comment by 7sxzx** [comment]
@endrureza 
I'm actually facing the exact same issue.

Could you please please tell me how did you resolve it?

**Comment by endrureza** [comment]
@7sxzx all i have to do is adding unique key as attribute

```
<SRLWrapper key="unique-value" />
```

**Comment by 7sxzx** [comment]
@endrureza 
I tried that, but unfortunately couldn't resolve the issue.

Do you know any other alternative to it?

**Comment by michelecocuccio** [comment]
@7sxzx are you able to reproduce this issue on a Code Sandbox? I would like to see how people is facing this issue as I am not facing this issue in any way I try.

**Comment by 7sxzx** [comment]
This is the code snippet almost same a real case.

```
ProductDetail.js
-----------------------

const [lightboxImages, setLightboxImages] = useState(null)

  useEffect(() => {
    if (images) {
      setLightboxImages(
        images.map((img) => ({
          src: img.url,
          thumbnail: img.thumbnail,
          caption: img.caption
        }))
      );
    }

    return () => {
      setLightboxImages(null);
    };
  }, [images]);

return (
.......
<ProductImage images={lightboxImages}/>
........
)


ProductImage.js
------------------------

  const { openLightbox } = useLightbox()

 const handleOpenLighbox = (src) => {
    openLightbox(index)
  }

return (
<button onClick={handleOpenLighbox}>Open Lightbox</button>
...........
<SRLWrapper
  key={id} //  prod id is passed each time new product detail page is requested
  callbacks={callbacks}
  options={{
    settings: {
      overlayColor: '#FFFFFF',
      disablePanZoom: true,
    },
    buttons: {
      showDownloadButton: false,
      showAutoplayButton: false,
      showThumbnailsButton: false,
    },
    thumbnails: {
      showThumbnails: true,
      thumbnailsPosition: 'left',
      thumbnailsOpacity: 0.4,
      thumbnailsGap: '8px 0',
      thumbnailsAlignment: 'center',
      thumbnailsSize: ['130px', '100px'],
    },
  }}
  images={images}
/>
...........
)

```
