### ISSUE TITLE
Feature request: Please add boxShadow prop to "Settings options"

### ISSUE THREAD

**Issue by msiric** [michelecocuccio/simple-react-lightbox#97]

**Comment by michelecocuccio** [comment]
@msiric hello.
Please be more specific. Box shadow for what? The lightbox takes 100% width and height of the screen so you won't be able to see any shadow I am afraid.

Thanks

**Comment by msiric** [comment]
@michelecocuccio 
I have a use case where I would like to add a box shadow behind the image when lightbox is open.
I understand there is a class for this, but that doesn't help since I am detecting the most prevalent color in every image and would like to add that color as a box shadow for every image respectively.
Hopefully that makes more sense.

Thanks

**Comment by michelecocuccio** [comment]
Hello.

this feature has been added with the version 3.5.0.
The documentation has been updated as well.

Thanks
