### ISSUE TITLE
Uncaught TypeError: t.apply is not a function

### ISSUE THREAD

**Issue by vishald256** [michelecocuccio/simple-react-lightbox#98]
**Bug**
When clicked on image, browser window goes blank, In console got error as follows, Uncaught TypeError: t.apply is not a function.

**Environment**
I'm using React App based theme for Wordpress and fetching HTML with REST API. I've already wrapped my App inside `<SimpleReactLightbox>` and wrapped `<SRLWrapper>` to a div where dynamic HTML content from API are going to set. Check screenshot below,

![Screenshot 2020-10-28 at 3 09 37 PM](https://user-images.githubusercontent.com/73584686/97419106-a9ed7180-192f-11eb-8242-e8276ce3a09b.png)

**Comment by michelecocuccio** [comment]
Hello @vishald256,

I don't have any "apply" function anywhere so I am not sure what it's causing this. I am not even sure is my lightbox or something else. I have only tested the lightbox with pure React code (Gatsby, NextJS or Create React App), never with WordPress so I can't really reproduce this. Unless you are able to create a CodeSandbox demo for me.

Thanks

**Comment by vishald256** [comment]
Sorry for delayed response, It seems some configuration issue with webpack, This issue appearing only after generating build with webpack, Could you please help ?
`> webpack -p

Hash: b342fc17defde21ea4cf
Version: webpack 3.12.0
Time: 15238ms
                  Asset     Size  Chunks                    Chunk Names
 images/placeholder.jpg  97.5 kB          [emitted]         
images/loading-icon.gif  84.9 kB          [emitted]         
                 app.js   705 kB       0  [emitted]  [big]  app
              style.css   1.2 kB       0  [emitted]         app
  [17] ./src/not-found.jsx 3.98 kB {0} [built]
  [24] (webpack)/buildin/global.js 509 bytes {0} [built]
  [47] ./src/elements/category.jsx 4.61 kB {0} [built]
  [90] ./src/index.jsx 11.4 kB {0} [built]
 [211] ./src/header.jsx 8.96 kB {0} [built]
 [233] ./src/footer.jsx 7.32 kB {0} [built]
 [238] ./src/posts.jsx 5.92 kB {0} [built]
 [301] ./src/post.jsx 6.17 kB {0} [built]
 [302] ./src/author.jsx 4.51 kB {0} [built]
 [303] ./src/about-us.jsx 4.74 kB {0} [built]
 [310] ./src/careers.jsx 2.83 kB {0} [built]
 [311] ./src/e-waste.jsx 13.2 kB {0} [built]
 [312] ./src/page.jsx 8.49 kB {0} [built]
 [313] ./src/home.jsx 6.25 kB {0} [built]
 [338] ./src/style.scss 41 bytes {0} [built]
    + 324 hidden modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/dist/cjs.js!src/style.scss:
       [0] ./node_modules/css-loader!./node_modules/sass-loader/dist/cjs.js!./src/style.scss 1.36 kB {0} [built]
        + 1 hidden module`

It's unable to create global.js, Here is my webpack configuration,

`var ExtractTextPlugin = require("extract-text-webpack-plugin");
var path = require("path");

module.exports = {
  entry: {
    app: "./src/index.jsx"
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "[name].js"
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: ["css-loader", "sass-loader"],
          publicPath: "dist"
        })
      },
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: "babel-loader"
      },
      {
        test: path.resolve('./src/globals.js'),
        use:
          'exports-loader?type=commonjs&exports[]=file&exports[]=multiple|helpers.parse|parse',
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        use: [
          "file-loader?name=[name].[ext]&outputPath=images/&publicPath=http://servifyinwp.com/wp-content/themes/servify-feb-2020/dist/images",
          "image-webpack-loader"
        ]
      },
      {
        test: /\.(woff2?|svg)$/,
        loader: "url-loader?limit=10000&name=fonts/[name].[ext]"
      },
      {
        test: /\.(ttf|eot)$/,
        loader: "file-loader?name=fonts/[name].[ext]"
      }
    ]
  },
  resolve: {
    extensions: [".js", ".jsx"]
  },
  plugins: [
    new ExtractTextPlugin({
      filename: "style.css",
      allChunks: true
    })
  ]
};
`

Let me know what I'm missing.

**Comment by michelecocuccio** [comment]
@vishald256 your code is not formatted properly and unfortunately I am afraid that configuration with WebPack is out of the scope of this issue. I am not sure if you are doing something wrong with your WebPack config... Maybe you can try to reproduce your configuration in a CodeSandbox environment so I can take a proper look?
